### ISSUE TITLE
How to get twitter data with keyword and within certain location and time

### ISSUE THREAD

**Issue by minsung-k** [JustAnotherArchivist/snscrape#310] opened 2021-11-21 05:51 UTC
Hi, if the code looks like that I can only get a keyword and time data. geocode does not work in that case.
Can I ask how to change it?

```python3
# Creating list to append tweet data to
tweets_list2 = []

loc = '26.304502, -80.269455, 10km'
# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('Stoneman Douglas High School geocode:"{}" since:2018-02-10 until:2018-02-18'.format(loc)).get_items()):
    if i>50:
        break
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.user.location, tweet.user.username])
    
# Creating a dataframe from the tweets list above
tweets_df2 = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'Location','Username'])
tweets_df2.to_csv("twitter data.csv")
```

**Comment by JustAnotherArchivist** [comment] 2021-11-21 06:18
Works fine for me. More specifically, this simplified version without the non-snscrape parts:

```python3
import snscrape.modules.twitter

loc = '26.304502, -80.269455, 10km'
# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(snscrape.modules.twitter.TwitterSearchScraper('Stoneman Douglas High School geocode:"{}" since:2018-02-10 until:2018-02-18'.format(loc)).get_items()):
	print(tweet.json())
	break
```

**Comment by minsung-k** [comment] 2021-11-21 06:43
Yes, it runs.
but the geocode condition does not apply in the result(location).

The output is "location": "Nashville, TN" when I ran your code, and only when I deleted the date(since:2018-02-10 until:2018-02-18), "location": "Coral Springs, FL" which is what I expected when I set in geocode.

I saw the 50 tweets in my code's dataframe, geocode doesn't work when I specified the date.

**Comment by JustAnotherArchivist** [comment] 2021-11-21 06:50
It does filter correctly. The `geocode` filter applies to the tweet geotags, not the user profile location info (which in this case is Nashville, TN). In the case of the first result to that query (tweet 965010006721613829), the former is this:

```json
    "coordinates": {
        "_type": "snscrape.modules.twitter.Coordinates",
        "longitude": -80.26934344242832,
        "latitude": 26.323587464680763
    },
    "place": {
        "_type": "snscrape.modules.twitter.Place",
        "fullName": "Parkland Amphitheater",
        "name": "Parkland Amphitheater",
        "type": "poi",
        "country": "United States",
        "countryCode": "US"
    },
```

I didn't check, but that's reasonably close to the coordinates you specified.

**Comment by minsung-k** [comment] 2021-11-21 06:59
Oh, I understand what you are saying.

Thank you so much!

**Comment by JustAnotherArchivist** [comment] 2021-11-21 07:24
No problem. :-)

Duplicate of #271

**Closed** 2021-11-21 07:24 UTC
Labels: duplicate
