### ISSUE TITLE
How to use Snscrape for basic scraping calls

### ISSUE THREAD

**Issue by nv78** [JustAnotherArchivist/snscrape#665] opened 2023-01-13 03:05 UTC
This code used to work for twitter, but now does not. Can you do something like this for similar websites, like instagram, reddit, and facebook for instance with this repo?
```
import snscrape.modules.twitter as sntwitter
import pandas as pd
from datetime import date

def get_tweets_from_user(
    user: str = 'john',
    n_tweets: int = 150
) -> pd.DataFrame:
    # To Run: get_tweets_from_user('john', n_tweets=15)

    query = "from:" + str(user)
    # Created a list to append all tweet attributes(data)
    attributes_container = []

    # Using TwitterSearchScraper to scrape data and append tweets to list
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
        if i>n_tweets:
            break
        attributes_container.append([tweet.date, tweet.likeCount, tweet.sourceLabel, tweet.content])

    # Creating a dataframe from the tweets list above
    tweets_df = pd.DataFrame(attributes_container, columns=["Date Created", "Number of Likes", "Source of Tweet", "Text"])

    return tweets_df

def search_tweets(
    search_query: str,
    n_tweets: int = 150,
    start_date: str = "2022-06-06",
    end_date: str = "2022-07-06",
) -> pd.DataFrame:
    # To Run: search_tweets('arsenal soccer', '2022-06-06' ,'2022-07-06', n_tweets=15)

    query = str(search_query) + " since:" + str(start_date) + " until:" + str(end_date)
    # Creating list to append tweet data to
    attributes_container = []

    # Using TwitterSearchScraper to scrape data and append tweets to list
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query, top=False).get_items()):
        if i>n_tweets:
            break
        attributes_container.append([tweet.user.username, tweet.date, tweet.likeCount, tweet.sourceLabel, tweet.content])

    # Creating a dataframe to load the list
    tweets_df = pd.DataFrame(attributes_container, columns=["User", "Date Created", "Number of Likes", "Source of Tweet", "Text"])

    return tweets_df

get_tweets_from_user("elonmusk")

search_tweets("New York City")
```

**Comment by JustAnotherArchivist** [comment] 2023-01-13 03:26
Duplicate of #634

**Closed by JustAnotherArchivist** 2023-01-13 03:26 UTC
Labels: duplicate

**Comment by JustAnotherArchivist** [comment] 2023-01-13 03:28
Yes, there are scrapers for other sites, as listed in the README. There are also numerous examples in other issues as well as various bugs, especially on Facebook and Instagram. Please search the existing issues.

**Comment by Aravindh-123** [comment] 2023-01-13 07:31
Same Question for me How to use basic scrape for facebook user and facebook page I try this :

for i, fb_data in enumerate(fbscrape.FacebookUserScraper('Aravindh').get_items()):
    if i >= 10:
        break
    else:
        fb.append([fb_data.content, fb_data.date])

It return []

How to solve this ?
