### ISSUE TITLE
Instagram hashtag scraper fails on non-ASCII hashtags

### ISSUE THREAD

**Issue by rgb-panda** [JustAnotherArchivist/snscrape#233] opened 2021-05-26 23:23 UTC
Hello,

I'm trying to scrape Instagram for Arabic hashtags, but getting Hashtag doesn't exist when searching with normal letters

snscrape --jsonl --with-entity --max-results 10 instagram-hashtag أوريو

This is the link for the hashtag, it has around 36k posts

https://www.instagram.com/explore/tags/أوريو/

Using the unicode of it though works, but produces the file with unicode content as well

**Example**:

snscrape --jsonl --with-entity --max-results 10 instagram-hashtag %D8%A3%D9%88%D8%B1%D9%8A%D9%88

{"_type": "snscrape.modules.instagram.InstagramPost", "cleanUrl": "https://www.instagram.com/p/CPWrS3lBn0u/", "dirtyUrl": "https://www.instagram.com/p/CPWrS3lBn0u/?taken-by=", "date": "2021-05-26T23:18:07+00:00", "content": "\ud83d\ude0d \u062a\u0639\u0644\u064a\u0642\u0643\u0645\n\n: . . . . #lezzeti #\u0639\u0634\u0627\u0621 #\u0641\u0637\u0648\u0631_\u0635\u0628\u0627\u062d\u064a #\u064a\u0645\u064a_\u064a\u0645\u064a #\u064a\u0645\u064a_\u062c\u062f\u0629 #\u0639\u0634_\u0627\u0644\u0628\u0644\u0628\u0644 #\u0639\u0633\u0644_\u0637\u0628\u06cc\u0639\u06cc #\u0645\u0639\u062c\u0646\u0627\u062a\u064a #\u062a\u0648\u0631\u062a\u064a\u0644\u0627 #\u062e\u0628\u0632_\u0635\u0627\u062c #\u0648\u0635\u0641\u0627\u062a_\u0646\u0648\u0631 #\u0648\u0635\u0641\u0629_\u0633\u0647\u0644\u0629 #\u062d\u0644\u0649_\u0643\u0627\u0633\u0627\u062a #\u062d\u0644\u0649_\u0644\u0630\u064a\u0630 #\u062d\u0644\u0649_\u0627\u0644\u0644\u0648\u062a\u0633 #\u0627\u0654\u0648\u0631\u064a\u0648 #dessert #\u0633\u0644\u0637\u0647_\u0633\u064a\u0632\u0631 #\u0633\u0644\u0637\u0627\u062a\u064a #\u0645\u0642\u0628\u0644\u0627\u062a_\u062e\u0641\u064a\u0641\u0647 #\u062d\u0644\u0649 #\u0633\u0646\u0639\u0627\u062a #\u0641\u0637\u064a\u0631\u0629 #\u0643\u0646\u0627\u0641\u0629_\u0646\u0627\u0628\u0644\u0633\u064a\u0629 #\u062d\u0644\u0648\u064a\u0627\u062a_\u0634\u0631\u0642\u064a\u0629#\u062d\u0644\u0627_\u0628\u0627\u0633\u0643\u0646_\u0631\u0648\u0628\u0646\u0632 #\u0628\u0627\u0633\u0643\u0646_\u0631\u0648\u0628\u0646\u0632 #\u0628\u0627\u0633\u0643\u0646_\u0631\u0648\u0628\u0646\u0632_\u0643\u064a\u0643\u0647_\u0627\u0653\u064a\u0633\u0643\u0631\u064a\u0645 #\u0631\u0648\u0628\u0646\u0632_\u0643\u064a\u0643\u0647_\u0622\u064a\u0633\u0643\u0631\u064a\u0645\"", "thumbnailUrl": "https://instagram.fykz2-1.fna.fbcdn.net/v/t51.2885-15/e35/191826431_117557060452529_6737428432876708933_n.jpg?tp=1&_nc_ht=instagram.fykz2-1.fna.fbcdn.net&_nc_cat=105&_nc_ohc=FoO8HJCI3SYAX-y1jrn&edm=ABZsPhsBAAAA&ccb=7-4&oh=d603413ae4e5c2fcd19d48997a4b1ad2&oe=60B0DC78&_nc_sid=4efc9f", "displayUrl": "https://instagram.fykz2-1.fna.fbcdn.net/v/t51.2885-15/e35/191826431_117557060452529_6737428432876708933_n.jpg?tp=1&_nc_ht=instagram.fykz2-1.fna.fbcdn.net&_nc_cat=105&_nc_ohc=FoO8HJCI3SYAX-y1jrn&edm=ABZsPhsBAAAA&ccb=7-4&oh=d603413ae4e5c2fcd19d48997a4b1ad2&oe=60B0DC78&_nc_sid=4efc9f", "username": "", "likes": 1, "comments": 0, "commentsDisabled": false, "isVideo": true}

Is there a way to resolve this in snscrape, or do I need to handle conversions outside?

Thanks,

**Comment by JustAnotherArchivist** [comment] 2021-05-26 23:43
The first command is supposed to work, so that's a bug. Thanks for the report!

The output is valid. This is JSON, and encoding non-ASCII characters like that is what Python does by default so the output is independent of any character encoding. I suppose I could experiment with `ensure_ascii = False`, but you're going to need a JSON parser anyway to process that data further, so I don't really see the value in that.

**Comment by JustAnotherArchivist** [comment] 2021-09-21 20:04
I cannot reproduce this bug now. `snscrape --jsonl --with-entity --verbose --max-results 10 instagram-hashtag أوريو` works correctly for me. I don't remember whether I tested this back in May. But there were no code changes in the Instagram scraper that would be of relevance to this, and I can't imagine that requests changed anything about the percent-encoding without mentioning it in the changelog. As such, I'm closing this as invalid.

If anyone can reproduce it, I'd be interested in hearing the details, in particular on terminal/shell configuration. My suspicion is that the argument is not passed as UTF-8 for whatever reason.

**Closed by JustAnotherArchivist** 2021-09-21 20:04 UTC
Labels: bug, module:instagram
