### ISSUE TITLE
Pythonanywhere snscrape.base.ScraperException: 4 requests to error

### ISSUE THREAD

**Issue by HAKANMAZI** [JustAnotherArchivist/snscrape#217] opened 2021-04-18 10:49 UTC
Hi @JustAnotherArchivist , I try to use your snscrape on Pythonanywhere platform I am getting this error. On my locally I don't get an error.

> 2021-04-18 10:57:33,878: Retrieving scroll page None
> 2021-04-18 10:57:33,879: Retrieving guest token
> 2021-04-18 10:57:33,883: Retrieving https://twitter.com/search?f=live&lang=en&q=from%3AProjects_007+since%3A2020-11-01+until%3A2021-01-01+&src=spelling_expansion_revert_click
> 2021-04-18 10:57:35,917: Error retrieving https://twitter.com/search?f=live&lang=en&q=from%3AProjects_007+since%3A2020-11-01+until%3A2021-01-01+&src=spelling_expansion_revert_click: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /search?f=live&lang=en&q=from%3AProjects_007+since%3A2020-11-01+until%3A2021-01-01+&src=spelling_expansion_revert_click (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f21875a9850>: Failed to establish a new connection: [Errno 111] Connection refused'))")), retrying
> 2021-04-18 10:57:35,917: Waiting 1 seconds
> 2021-04-18 10:57:36,919: Retrieving https://twitter.com/search?f=live&lang=en&q=from%3AProjects_007+since%3A2020-11-01+until%3A2021-01-01+&src=spelling_expansion_revert_click
> 2021-04-18 10:57:38,958: Error retrieving https://twitter.com/search?f=live&lang=en&q=from%3AProjects_007+since%3A2020-11-01+until%3A2021-01-01+&src=spelling_expansion_revert_click: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /search?f=live&lang=en&q=from%3AProjects_007+since%3A2020-11-01+until%3A2021-01-01+&src=spelling_expansion_revert_click (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f21875a9b80>: Failed to establish a new connection: [Errno 111] Connection refused'))")), retrying
> 2021-04-18 10:57:38,958: Waiting 2 seconds
> 2021-04-18 10:57:40,961: Retrieving https://twitter.com/search?f=live&lang=en&q=from%3AProjects_007+since%3A2020-11-01+until%3A2021-01-01+&src=spelling_expansion_revert_click
> 2021-04-18 10:57:42,993: Error retrieving https://twitter.com/search?f=live&lang=en&q=from%3AProjects_007+since%3A2020-11-01+until%3A2021-01-01+&src=spelling_expansion_revert_click: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /search?f=live&lang=en&q=from%3AProjects_007+since%3A2020-11-01+until%3A2021-01-01+&src=spelling_expansion_revert_click (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f21875a9e80>: Failed to establish a new connection: [Errno 111] Connection refused'))")), retrying
> 2021-04-18 10:57:42,993: Waiting 4 seconds
> 2021-04-18 10:57:46,998: Retrieving https://twitter.com/search?f=live&lang=en&q=from%3AProjects_007+since%3A2020-11-01+until%3A2021-01-01+&src=spelling_expansion_revert_click
> 2021-04-18 10:57:49,037: Error retrieving https://twitter.com/search?f=live&lang=en&q=from%3AProjects_007+since%3A2020-11-01+until%3A2021-01-01+&src=spelling_expansion_revert_click: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /search?f=live&lang=en&q=from%3AProjects_007+since%3A2020-11-01+until%3A2021-01-01+&src=spelling_expansion_revert_click (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f21875ca1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"))
> 2021-04-18 10:57:49,037: 4 requests to https://twitter.com/search?f=live&lang=en&q=from%3AProjects_007+since%3A2020-11-01+until%3A2021-01-01+&src=spelling_expansion_revert_click failed, giving up.
> 2021-04-18 10:57:49,037: Exception on / [POST]
> Traceback (most recent call last):
>   File "/home/hak122hak/.virtualenvs/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/hak122hak/.virtualenvs/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/hak122hak/.virtualenvs/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/hak122hak/.virtualenvs/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/home/hak122hak/.virtualenvs/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/hak122hak/.virtualenvs/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/hak122hak/mysite/app.py", line 22, in index
>     userTweets_CSV(session['username'])
>   File "/home/hak122hak/mysite/app.py", line 9, in userTweets_CSV
>     for i, tweet in enumerate(twitter.TwitterSearchScraper('from:' +username+ ' since:2020-11-01 until:2021-01-01 ').get_items()):
>   File "/home/hak122hak/.virtualenvs/env/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 478, in get_items
>     for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams):
>   File "/home/hak122hak/.virtualenvs/env/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 245, in _iter_api_data
>     obj = self._get_api_data(endpoint, reqParams)
>   File "/home/hak122hak/.virtualenvs/env/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 225, in _get_api_data
>     self._ensure_guest_token()
>   File "/home/hak122hak/.virtualenvs/env/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 195, in _ensure_guest_token
>     r = self._get(self._baseUrl if url is None else url, headers = {'User-Agent': self._userAgent})
>   File "/home/hak122hak/.virtualenvs/env/lib/python3.8/site-packages/snscrape/base.py", line 196, in _get
>     return self._request('GET', *args, **kwargs)
>   File "/home/hak122hak/.virtualenvs/env/lib/python3.8/site-packages/snscrape/base.py", line 192, in _request
>     raise ScraperException(msg)
> snscrape.base.ScraperException: 4 requests to https://twitter.com/search?f=live&lang=en&q=from%3AProjects_007+since%3A2020-11-01+until%3A2021-01-01+&src=spelling_expansion_revert_click failed, givi

**Comment by JustAnotherArchivist** [comment] 2021-04-18 16:50
Although they don't say so very prominently, PythonAnywhere is hosted on AWS, hence this is a duplicate of #79.

**Closed by JustAnotherArchivist** 2021-04-18 16:50 UTC
