### ISSUE TITLE
Twitter scrapping for specific location 

### ISSUE THREAD

**Issue by cjj1120** [JustAnotherArchivist/snscrape#251] opened 2021-07-06 10:10 UTC
Is it possible to query from two list of keywords (at least one keyword from both lists), and also if can add parameter to search for specific location will be great! So far this lib has been performing great and stable, hopefully more features can be added.

**Comment by JustAnotherArchivist** [comment] 2021-07-06 16:45
Thanks.

Twitter doesn't let you reliably search for geolocated tweets anymore since a couple years ago, so this is impossible to implement.

Duplicate of #145

**Closed** 2021-07-06 18:09 UTC
Labels: duplicate
