### ISSUE TITLE
How to get retweets in from capture?

### ISSUE THREAD

**Issue by psegovias** [JustAnotherArchivist/snscrape#541] opened 2022-08-31 14:31 UTC
Hi, im searching this in Twitter:

from:nasa include:nativeretweets

But that show me retweets made by the nasa account i looking for the user who has made a retweets to nasa.

**Comment by JustAnotherArchivist** [comment] 2022-08-31 18:02
Duplicate of #103

**Closed by JustAnotherArchivist** 2022-08-31 18:02 UTC
Labels: duplicate
