### ISSUE TITLE
AttributeError: module 'functools' has no attribute 'cached_property'

### ISSUE THREAD

**Issue by p-dre** [JustAnotherArchivist/snscrape#87] opened 2020-09-26 15:07 UTC
Hi, from one day to the other I get the following error.
I tried the code one another device and there the code is working. But I do not get It to fix on that device where I need it. 

`snscrape twitter-search "(to:MedicalTopJobs) since:2020-02-12 until:2020-02-22 filter:replies" >C:\\Users\\name\\Documents\\Uni\\Masterarbeit\\Datengewinnung\\Tweets_antworten\\Antworten\\antworten_SARS_CoV_1227638410191495168`

```
Traceback (most recent call last):
  File "c:\users\name\anaconda3\envs\nlp 2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\name\anaconda3\envs\nlp 2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\name\Anaconda3\envs\NLP 2\Scripts\snscrape.exe\__main__.py", line 7, in <module>
  File "c:\users\name\anaconda3\envs\nlp 2\lib\site-packages\snscrape\cli.py", line 251, in main
    args = parse_args()
  File "c:\users\name\anaconda3\envs\nlp 2\lib\site-packages\snscrape\cli.py", line 159, in parse_args
    import snscrape.base
  File "c:\users\name\anaconda3\envs\nlp 2\lib\site-packages\snscrape\base.py", line 55, in <module>
    class Scraper:
  File "c:\users\name\anaconda3\envs\nlp 2\lib\site-packages\snscrape\base.py", line 75, in Scraper
    @functools.cached_property
AttributeError: module 'functools' has no attribute 'cached_property'`
```

**Comment by JustAnotherArchivist** [comment] 2020-09-26 15:46
Duplicate of #75. You need Python 3.8.

**Closed by JustAnotherArchivist** 2020-09-26 15:46 UTC
Labels: duplicate
