### ISSUE TITLE
Scraping tweets throughout a set time frame.

### ISSUE THREAD

**Issue by hannahgkeel** [JustAnotherArchivist/snscrape#216] opened 2021-04-17 15:46 UTC
Is there some sort of keyword I could use to scrape tweets from a set time frame of a year randomly instead of only getting the "latest" tweets?

I just want 200k tweets that contain Uber from Feb 2020 to April 14th, 2021 and I was hoping there might be a feature/keyword I could add that would help me do this. Currently this returns only tweets from March and April 2021. The current command I am running is below if that helps. 

snscrape --jsonl --progress --max-results 200000 --since 2020-02-1 twitter-search "Uber lang:en until:2021-04-14" > uber200k.json

**Comment by JustAnotherArchivist** [comment] 2021-04-17 15:50
Duplicate of #164

**Closed by JustAnotherArchivist** 2021-04-17 15:50 UTC
