### ISSUE TITLE
snscrape: error: unrecognized arguments: --jsonl

### ISSUE THREAD

**Issue by Nicknameinmel** [JustAnotherArchivist/snscrape#93] opened 2020-09-29 03:39 UTC
Could you tell me why the --jsonl can not be recongized?
Many thanks

**My code:**
!snscrape --jsonl --since 2020-4-2 twitter-search '$sbux' > ./jsonl.txt

**Error**
usage: snscrape [-h] [--version] [-v] [--dump-locals] [--retry N] [-n N]
                [-f FORMAT] [--since DATETIME]
                {googleplus-user,telegram-channel,vkontakte-user,facebook-user,facebook-group,gab-user,gab-user-comments,gab-user-media,instagram-user,instagram-hashtag,instagram-location,twitter-search,twitter-thread,twitter-list-members,twitter-user,twitter-hashtag,twitter-list-posts}
                ...
snscrape: error: unrecognized arguments: --jsonl

**Comment by ylizama** [comment] 2020-09-29 03:56
I am having the same issue here. Is there any other option?

**Comment by MartinoMensio** [comment] 2020-09-29 08:26
Hi,
I had the same issue and, looking at the version history it looks like the support for JSONL was added on 12th August (https://github.com/JustAnotherArchivist/snscrape/commit/bf229414babbf37fffb7e1144182b6f01844be69), while the latest version on PyPI (0.3.4) is from 9th July.
So the solution is to install the development version with `pip3 install git+https://github.com/JustAnotherArchivist/snscrape.git`

Martino

**Comment by Nicknameinmel** [comment] 2020-09-29 10:47
> 
> 
> Hi,
> I had the same issue and, looking at the version history, it looks like the support for JSONL was added on 12th August ([bf22941](https://github.com/JustAnotherArchivist/snscrape/commit/bf229414babbf37fffb7e1144182b6f01844be69)), while the latest version on PyPI (0.3.4) is from 9th July.
> So the solution is to install the development version with `pip3 install git+https://github.com/JustAnotherArchivist/snscrape.git`
> 
> Martino

Thank you! it works!

**Comment by JustAnotherArchivist** [comment] 2020-09-29 17:37
Duplicate of #77

**Closed by JustAnotherArchivist** 2020-09-29 17:37 UTC
