### ISSUE TITLE
snscrape.modules.twitter.TwitterSearchScraper

### ISSUE THREAD

**Issue by JJery-web** [JustAnotherArchivist/snscrape#491] opened 2022-06-13 03:41 UTC
Once again, I would like to express my admiration for this project.
But recently I've been using **snscrape.modules.twitter.TwitterSearchScraper**, it is found that some users' twitter will not be scraped.
For example, the following code:

```python3
import snscrape. modules. twitter
scraper = snscrape. modules. twitter. TwitterSearchScraper('(from:Odyssey_Basel)')
for tweet in scraper. get_ items():
	print(tweet)
```

Returned:
https://twitter.com/Odyssey_Basel/status/936308240945729536
https://twitter.com/Odyssey_Basel/status/934518354953596928
https://twitter.com/Odyssey_Basel/status/934041699428524032
https://twitter.com/Odyssey_Basel/status/933943091677093888
https://twitter.com/Odyssey_Basel/status/933602003334426624
https://twitter.com/Odyssey_Basel/status/933592219768053760
https://twitter.com/Odyssey_Basel/status/933585561935327232
https://twitter.com/Odyssey_Basel/status/821363615181733889
https://twitter.com/Odyssey_Basel/status/821363411678298116
https://twitter.com/Odyssey_Basel/status/821362988821184512
https://twitter.com/Odyssey_Basel/status/821362708171911168
https://twitter.com/Odyssey_Basel/status/821362254989971456
https://twitter.com/Odyssey_Basel/status/817083347289731073
https://twitter.com/Odyssey_Basel/status/816214215761469440
https://twitter.com/Odyssey_Basel/status/809722282549608450

In fact, I found that there are two items that I haven't scraped:
https://twitter.com/Odyssey_Basel/status/938843162700865537?cxt=HHwWgoC3ybu4uIcaAAAA
https://twitter.com/Odyssey_Basel/status/937757912818180096?cxt=HHwWgIC37c32yoMaAAAA

What is the matter with this situation? I only used "from", not since and until.

**Comment by JustAnotherArchivist** [comment] 2022-06-13 12:20
Twitter's search does not return them for whatever reason. Their index is sometimes weird. Nothing snscrape can do about that I'm afraid.

Duplicate of #468.

**Closed by JustAnotherArchivist** 2022-06-13 12:20 UTC
