### ISSUE TITLE
Error when scrape reddit

### ISSUE THREAD

**Issue by yudeng2022** [JustAnotherArchivist/snscrape#573] opened 2022-10-20 16:30 UTC
Hi 
I am using the following code to search 'steroid' but get the error message: 

> ScraperException: 4 requests to https://api.pushshift.io/reddit/search/submission/?q=steroid&size=1000&sort=desc failed, giving up. 

Any idea how to fix it?
```
scraper = snscrape.modules.reddit.RedditSearchScraper('steroid')
for i, item in enumerate(scraper.get_items()):
	print(item.json())
	if i >= 10:
		break
```

**Comment by JustAnotherArchivist** [comment] 2022-10-20 19:35
Full output please for both `snscrape -n 10 -v reddit-search steroid` and `snscrape --version`.

**Comment by yudeng2022** [comment] 2022-10-26 17:47
so I got 'snscrape' is not recognized as an internal or external command, operable program or batch file. even though the installation seems to be successful ...

**Comment by JustAnotherArchivist** [comment] 2022-10-27 17:50
Well, clearly something in your environment is wrong. But I'm afraid I can't help you with that since there are so many different ways how Python, pip, and snscrape could be installed and executed.

**Comment by JustAnotherArchivist** [comment] 2022-11-03 16:29
Closing this as it isn't reproducible or actionable. Given the broken installation, I'll bet this is caused by other issues in the environment, perhaps a broken network configuration.

**Closed by JustAnotherArchivist** 2022-11-03 16:29 UTC
