### ISSUE TITLE
Question about the time range parameters

### ISSUE THREAD

**Issue by ronming1303** [JustAnotherArchivist/snscrape#576] opened 2022-10-27 02:05 UTC
Hey guys, 

Any one has idea how to modify the time range parameters in the TwitterSearchScraper. I want to search the twitter within an hour of a day. (e.g. since: 2020-06-01 14:00:00 until 2020-06-01 15:00:00), how can I do that? FYI, below is my code. 

Thanks in advance.

```
# Creating list to append tweet data to
tweets_list2 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('bitcoin since:2020-06-01 until:2020-06-02').get_items()):
    if i>dailyMaxCount:
        break
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.url])
```

**Comment by JustAnotherArchivist** [comment] 2022-10-27 12:30
Duplicate of #259

**Closed by JustAnotherArchivist** 2022-10-27 12:30 UTC
