### ISSUE TITLE
retweet counts getting blank

### ISSUE THREAD

**Issue by PragnakalpDev29** [JustAnotherArchivist/snscrape#916] opened 2023-05-26 06:28 UTC
### Describe the bug

I am using the version "snscrape 0.6.2.20230321.dev13+g786815d"
 getting blank in the retweet counts

### How to reproduce
```python3
import os
# import sys
import snscrape.modules.twitter as sntwitter
import pandas as pd
import json

Username = "abcd"

PLATFORM_NAME = os.environ.get('PLATFORM_NAME')


scraper = sntwitter.TwitterSearchScraper(f"(from:{Username})")
tweets = []
for i, tweet in enumerate(scraper.get_items()):
    print(tweet)
    # data=[tweet.id,tweet.content,tweet.user.username,tweet.likeCount,tweet.retweetCount,tweet.replyCount]
    data = {
        "id_post": tweet.id,
        "Date": tweet.date.strftime("%Y-%m-%d"),
        "Heure": tweet.date.strftime("%H:%M:%S"),
        "content": tweet.content,
        "username": tweet.user.username,
        "likecount": tweet.likeCount,
        "retweetcount": tweet.retweetCount,
        "replycount": tweet.replyCount,

    }
    tweets.append(data)
    if i > 80:
        break

tweet_df = pd.DataFrame(tweets, columns=["id_post","Date","Heure", "content", "username", "likecount", "reteweetcount", "replycount","platformname"])
tweet_df.to_csv('output.csv', index=False)

tweet_json = tweet_df.to_json(orient='records', indent=4)
print(tweet_json.encode('utf-8').decode('utf-8'))
```

### Expected behaviour

rfe

### Operating system

Ubuntu 20.04

### Python version: output of `python3 --version`

Python 3.8.10

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230321.dev13+g786815d

### Scraper

twitter

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment] 2023-05-26 16:40
This looks like a duplicate of #911.

**Comment by PragnakalpDev29** [comment] 2023-05-27 05:20
Which version we should use to getting retweet count?

**Comment by JustAnotherArchivist** [comment] 2023-05-27 12:39
The latest dev version should work. Your example is clearly not what you're actually using though since the user abcd is suspended. Until I can reproduce the issue, I can't fix anything.

Closing this in favour of #911.

**Closed by JustAnotherArchivist** 2023-05-27 12:39 UTC
Labels: duplicate
