### ISSUE TITLE
TwitterProfileScraper doesn't seem to work

### ISSUE THREAD

**Issue by tsaaii** [JustAnotherArchivist/snscrape#421] opened 2022-03-07 03:10 UTC
Hi,

I am trying to print retweets of a given user but it gives a blocked (429) error.

Is this not possible anymore? I can use other methods without any problem.

**Comment by JustAnotherArchivist** [comment] 2022-03-07 03:24
Duplicate of #367

**Closed by JustAnotherArchivist** 2022-03-07 03:24 UTC
