### ISSUE TITLE
facebook scrap?

### ISSUE THREAD

**Issue by Aravindh-123** [JustAnotherArchivist/snscrape#666] opened 2023-01-13 08:39 UTC
How to use basic scrape for facebook user and facebook page I try this :

```python
for i, fb_data in enumerate(fbscrape.FacebookUserScraper('Aravindh').get_items()):
    if i >= 10:
        break
    else:
        fb.append([fb_data.content, fb_data.date])
```

It return []

How to solve this ?

**Comment by JustAnotherArchivist** [comment] 2023-01-13 08:52
The Facebook module is very broken. They redesigned the website, and that is not supported by snscrape yet. They have awful rate limits, which makes efficient development very difficult, so I gave up on it. There are several open issues about these things.

**Comment by JustAnotherArchivist** [comment] 2023-01-13 20:00
Duplicate of #523

**Closed by JustAnotherArchivist** 2023-01-13 20:00 UTC
Labels: duplicate
