### ISSUE TITLE
__init__() missing 1 required positional argument: 'title'

### ISSUE THREAD

**Issue by dmartin5150** [JustAnotherArchivist/snscrape#428] opened 2022-03-13 03:05 UTC
I am getting this message with the following code:

import snscrape.modules.twitter as sntwitter
import pandas

# Creating list to append tweet data to
tweets_list2 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i, tweet in enumerate(snscrape.modules.twitter.TwitterSearchScraper('COVID Vaccine since:2021-01-01 until:2021-06-30').get_items()):
# for i, tweet in enumerate(snscrape.modules.twitter.TwitterSearchScraper('COVID Vaccine since:2021-01-01 until:2021-05-31').get_items()):
    if i>500:
        break
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
    
# Creating a dataframe from the tweets list above
tweets_df2 = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])

**Comment by JustAnotherArchivist** [comment] 2022-03-13 03:06
Duplicate of #407

**Closed by JustAnotherArchivist** 2022-03-13 03:06 UTC
