### ISSUE TITLE
ScraperException: 4 requests failed after multiple hours of scraping

### ISSUE THREAD

**Issue by veronicasrfn** [JustAnotherArchivist/snscrape#609] opened 2022-12-02 09:06 UTC
Hello! I am getting the following error after multiple hours of running:

ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28bitcoin+OR+btc%29+%28%23bitcoin+OR+%23btc%29+lang%3Aen+until%3A2022-10-03+since%3A2019-08-23+-filter%3Areplies+-filter%3Asafe&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&cursor=scroll%3AthGAVUV0VFVBaAgLLl07Xj0CoWgICjvY3b0uErEnEV0NoUFYCJehgHREVGQVVMVDUBFcxVFQAA&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.

The code that I'm running on Spyder both from:
- Macbook M1 (2020) with macOS Monterey 12.5, Python version 3.9.13 and snscrape 0.4.3.20220106
- Macbook Intel (mid 2013) with macOS Catalina 10.15.4, Python version 3.9.13 and snscrape 0.4.3.20220106,
is the following:

```python3
import snscrape.modules.twitter as sntwitter
import pandas as pd

query = "(bitcoin OR btc) (#bitcoin OR #btc) lang:en until:2022-10-03 since:2019-08-23 -filter:replies (filter:safe OR -filter:safe)"
tweets = []

for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    tweets.append([tweet.date, tweet.user.username, tweet.user.verified, tweet.user.followersCount, tweet.likeCount, tweet.replyCount, tweet.retweetCount, tweet.quoteCount, tweet.lang, tweet.hashtags, tweet.content])      
            
df = pd.DataFrame(tweets, columns = ['Date', 'Username', 'User verified', 'Followers count', 'Like count', 'Reply Count', 'Retweet Count', 'Quote Count', 'Language', 'Hashtags', 'Tweet content'])

print(df)

df.to_csv("Run BTC _eng.csv")
```

As you can see, I added (filter:safe OR -filter:safe) to the query, as suggested here: https://github.com/JustAnotherArchivist/snscrape/issues/247 but I still got the same error.

Thank you very much in advance!

**Comment by JustAnotherArchivist** [comment] 2022-12-02 12:21
The URL in the error doesn't match your code.
The filter addition suggested in #247 is a specific workaround for users causing HTTP 400, not a general one for any scraping errors.
Unfortunately, this error is too generic to tell what happened there. I'll try to improve that (which has been on my todo list for a while anyway). It happening after hours is weird. I'm unable to reproduce it with a scrape starting from the request where it crashed for you. Will try to run the full thing later.

**Comment by Ashoka74** [comment] 2022-12-23 15:33
Same error here! 

Reddit won't be working until some time because there is an update in the Pushift API, see #619.

**Comment by asafkamer** [comment] 2023-01-12 06:21
i also get this error for my code :
            for tweet in sntwitter.TwitterSearchScraper(
                    f'{hashtag} since:{start_date.strftime("%Y-%m-%d")} until:{end_date.strftime("%Y-%m-%d")} lang:en').get_items():
                tweets_list.append(
                    [tweet.user.id, tweet.id, tweet.content, tweet.likeCount, tweet.retweetCount, tweet.place.fullName if tweet.place is not None else "Not available",
                     tweet.replyCount,
                     tweet.hashtags, len(tweet.mentionedUsers) if tweet.mentionedUsers is not None else 0, tweet.url, hashtag, tweet.date])

                # Save the tweet to the CSV file
                writer.writerow(
                    [tweet.user.id, tweet.id, tweet.content, tweet.likeCount, tweet.retweetCount, tweet.place.fullName if tweet.place is not None else "Not available",
                     tweet.replyCount,
                     tweet.hashtags, len(tweet.mentionedUsers) if tweet.mentionedUsers is not None else 0, tweet.url,hashtag, tweet.date])


                print(f"{tweet.content} - @{tweet.username}")

Errors: non-200 status code (404)

**Comment by JustAnotherArchivist** [comment] 2023-01-13 02:43
I could never reproduce this, and due to #634, it's impossible at least for the time being. The discrepancy between error message and code was never explained either. Closing.

**Closed by JustAnotherArchivist** 2023-01-13 02:43 UTC
Labels: module:twitter, incomplete
