### ISSUE TITLE
Error sntwitter while using query and TwitterSearchScraper: "4 requests to ... failed giving up"

### ISSUE THREAD

**Issue by FLXNO** [JustAnotherArchivist/snscrape#643] opened 2023-01-11 11:28 UTC
Up until this morning I successfully used snscrape to scrape twitter tweets via python. The code looks like this:

`import snscrape.modules.twitter as sntwitter
query = "from:annewilltalk"
for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
     # do stuff`

But this morning without any changes I got the error:

`Traceback (most recent call last):
File "twitter.py", line 568, in <module>
    Scraper = TwitterScraper()
  File "twitter.py", line 66, in __init__
    self.get_tweets_talkshow(username = "annewilltalk")
  File "twitter.py", line 271, in get_tweets_talkshow
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
  File "/home/pi/.local/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 1455, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', _TwitterAPIType.V2, params, paginationParams, cursor = self._cursor):
  File "/home/pi/.local/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 721, in _iter_api_data
    obj = self._get_api_data(endpoint, apiType, reqParams)
  File "/home/pi/.local/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 691, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
  File "/home/pi/.local/lib/python3.8/site-packages/snscrape/base.py", line 221, in _get
    return self._request('GET', *args, **kwargs)
  File "/home/pi/.local/lib/python3.8/site-packages/snscrape/base.py", line 217, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=from%3Aannewilltalk&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo failed, giving up.`

I found online, that the URL encoding must not exceed a length of 500 and the one from the error message is about 800 long. Could that be the problem? Why did that change overnight? How can I fix that?

**Comment by marrcco** [comment] 2023-01-11 11:30
Twitter removed the Latest tab from their website(if you're not logged in), so API can't really get any data from the Latest tab, coz it doesn't exist.

**Comment by Andreagiordano99** [comment] 2023-01-11 11:50
You know if is there a solution?

**Comment by marrcco** [comment] 2023-01-11 12:03
currently, there's no workaround

**Comment by TavoAdr** [comment] 2023-01-11 13:23
Today I started having this error too ("4 requests to ... failed giving up"), I don't understand why, before it was working

This happens when I try through the terminal and code

`snscrape --jsonl twitter-search '#PublicTransit since:2019-03-01 until:2021-05-01 near:"New York"'`
(random command I found googled about)

`[print(s) for s in snscrape.modules.twitter.TwitterHashtagScraper('hashtag').get_items()]`
(random code for testing)

**Comment by CainDelta** [comment] 2023-01-11 14:58
I truly hate Elon Musk and his endless tampering with a working product

**Comment by AhmetcanFR** [comment] 2023-01-11 15:04
> I truly hate Elon Musk and his endless tampering with a working product

Bro that's crazy, legit saying the same since I woke up to this

**Comment by FLXNO** [comment] 2023-01-11 18:13
> Twitter removed the Latest tab from their website(if you're not logged in), so API can't really get any data from the Latest tab, coz it doesn't exist.

Just to be sure, because I really would need this to work again: Is there no other option to use the library without twitter having the "latest" tab???

**Comment by JustAnotherArchivist** [comment] 2023-01-11 18:39
Duplicate of #634

**Closed by JustAnotherArchivist** 2023-01-11 18:39 UTC
Labels: duplicate

**Comment by hduzcu27** [comment] 2023-09-18 10:59
has anyone solved the problem? It gives me the same error in my code.
