### ISSUE TITLE
Expecting 'EOF', '}', ',', ']', got '{'

### ISSUE THREAD

**Issue by xavierborgas** [JustAnotherArchivist/snscrape#275] opened 2021-09-08 08:37 UTC
Hi all, 

Unsure if this is the place to ask this question but I am stumped on this. I am new at coding in general but have managed to use SNSCRAPE to get a dataset of 500 tweets by following tutorials, though I cant manage to export this Json file into anything else. When I go to a Json Validator, I get the following message: 

```
Error: Parse error on line 110:
...	"cashtags": null} {	"_type": "snscrap
----------------------^
Expecting 'EOF', '}', ',', ']', got '{'
```

This is the text for reference:

```
		"country": "New Zealand",
		"countryCode": "NZ"
	},
	"hashtags": null,
	"cashtags": null
} {
	"_type": "snscrape.modules.twitter.Tweet",
	"url": "https://twitter.com/veeveekookie/status/1435510670401761285",
	"date": "2021-09-08T07:49:48+00:00",
	"content": "Try lang ulit, baka madaan pa sa practice \ud83e\udd72 https://t.co/VWUVxKsPhj",
	"renderedContent": "Try lang ulit, 
```

How do I resolve this? My end goal is to export this into Excel so that I can transfer the data across to Nvivo and perform sentiment/thematic analysis. 

Cheers, 
Xavier

**Comment by JustAnotherArchivist** [comment] 2021-09-08 19:18
`snscrape --jsonl` does not produce JSON; it produces JSONL, also known as NDJSON or LDJSON. Each line in the output is valid JSON, but the output as a whole is not.

**Comment by JustAnotherArchivist** [comment] 2021-09-10 20:03
Duplicate of #227

**Closed by JustAnotherArchivist** 2021-09-10 20:03 UTC
