### ISSUE TITLE
Instagram Error

### ISSUE THREAD

**Issue by Botami143** [JustAnotherArchivist/snscrape#560] opened 2022-09-26 10:22 UTC
![Screenshot 2022-09-26 154856](https://user-images.githubusercontent.com/77289273/192253369-3faa3cb0-a02e-451a-a563-e1103535c708.png)

### how to solve this error

**Comment by TheTechRobo** [comment] 2022-09-26 12:14
Duplicate of #520

**Comment by Botami143** [comment] 2022-09-28 10:23
How can I fix it?

**Closed** 2022-09-29 01:38 UTC
Labels: duplicate
