### ISSUE TITLE
Format --jsonl don't work

### ISSUE THREAD

**Issue by marcoferre** [JustAnotherArchivist/snscrape#136] opened 2020-10-25 11:04 UTC
Hi! i'm trying to get data in .json format but it doesn't work.

this is my command line:
`!snscrape --jsonl --max-results 10 twitter-search "#somehashtag since:2019-12-31 until:2020-09-25"`

and it gets this error

`usage: snscrape [-h] [--version] [-v] [--dump-locals] [--retry N] [-n N]
                [-f FORMAT] [--since DATETIME]
                {telegram-channel,googleplus-user,vkontakte-user,facebook-user,facebook-group,twitter-search,twitter-thread,twitter-list-members,gab-user,gab-user-comments,gab-user-media,instagram-user,instagram-hashtag,instagram-location,twitter-user,twitter-hashtag,twitter-list-posts}
                ...
snscrape: error: unrecognized arguments: --jsonl`

I'm executing this on a  google Colab page

Thanks!

**Comment by JustAnotherArchivist** [comment] 2020-10-25 12:53
Duplicate of #77

**Closed by JustAnotherArchivist** 2020-10-25 12:53 UTC
