### ISSUE TITLE
TypeError: Card.__init__() missing 1 required positional argument: 'title'

### ISSUE THREAD

**Issue by chr1s-p** [JustAnotherArchivist/snscrape#435] opened 2022-03-26 00:24 UTC
Hi, this is my code:

```python3
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('onlyfans.com/').get_items()):

  tweets_list2.append([
    tweet.date, 
    tweet.content, 
    tweet.user.username, 
    tweet.user.id,
    tweet.user.created, 
    tweet.user.followersCount,
    tweet.user.statusesCount,
    tweet.user.description, 
    tweet.user.linkUrl,
    tweet.user.descriptionUrls, 
    tweet.outlinks])
```

It ran fine, fetching 2390 tweets. However, it then crashed and produced this error: 

```
TypeError: Card.__init__() missing 1 required positional argument: 'title'
```

Full error: 

```
Traceback (most recent call last):
  File "c:\Users\Desktop\new_scraper\tweet_scraper.py", line 15, in <module>
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper('onlyfans.com/').get_items()):
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\snscrape\modules\twitter.py", line 811, in get_items
    yield from self._v2_timeline_instructions_to_tweets(obj)
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\snscrape\modules\twitter.py", line 488, in _v2_timeline_instructions_to_tweets
    yield from self._v2_instruction_tweet_entry_to_tweet(entry['entryId'], entry['content'], obj)
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\snscrape\modules\twitter.py", line 511, in _v2_instruction_tweet_entry_to_tweet
    yield self._tweet_to_tweet(tweet, obj)
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\snscrape\modules\twitter.py", line 642, in _tweet_to_tweet
    kwargs['card'] = self._make_card(tweet['card'], _TwitterAPIType.V2)
  File "C:\Users\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\snscrape\modules\twitter.py", line 632, in _make_card
    return Card(**cardKwargs)
TypeError: Card.__init__() missing 1 required positional argument: 'title'
```

Any ideas whats going `on?`

**Comment by TheTechRobo** [comment] 2022-03-26 00:49
Duplicate of #407

**Closed** 2022-03-26 01:53 UTC
Labels: duplicate
