### ISSUE TITLE
twitter-thread TypeError missing 6 required positional arguments

### ISSUE THREAD

**Issue by elig0n** [JustAnotherArchivist/snscrape#205] opened 2021-03-28 07:34 UTC
running `snscrape twitter-thread TWEET_ID` raise a traceback:
```
 CRITICAL  snscrape._cli  Dumped stack and locals to /tmp/snscrape_locals_id4qur3c
Traceback (most recent call last):
  File "/home/u/.local/bin/snscrape", line 8, in <module>
    sys.exit(main())
  File "/home/u/.local/lib/python3.9/site-packages/snscrape/_cli.py", line 270, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/home/u/.local/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 610, in get_items
    items = list(self._feed_to_items([tweet]))
  File "/home/u/.local/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 163, in _feed_to_items
    yield Tweet(url, date, content, tweetID, username, outlinks, ' '.join(outlinks), tcooutlinks, ' '.join(tcooutlinks))
TypeError: __init__() missing 6 required positional arguments: 'retweetCount', 'likeCount', 'quoteCount', 'conversationId', 'lang', and 'source'
```

**Comment by JustAnotherArchivist** [comment] 2021-03-28 21:48
Duplicate of #176

**Closed by JustAnotherArchivist** 2021-03-28 21:48 UTC
