### ISSUE TITLE
Cannot use 'twitter-profile' for scraping

### ISSUE THREAD

**Issue by marftabucks** [JustAnotherArchivist/snscrape#417] opened 2022-03-01 02:40 UTC
Hello. I'm planning to download all tweets, including the retweets, of a certain user. I found a reported issue #83 that mentioned an alternative of using a 'twitter-profile' for scraping. I tried the syntax `snscraper --progress twitter-profile jack`. However, the CLI showed messages like this

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/55443235/156094169-59956bd7-5d11-4ece-8fab-3d79a3a248a1.png">

Can anybody help me on this?

**Comment by JustAnotherArchivist** [comment] 2022-03-01 02:42
Duplicate of #367

**Closed by JustAnotherArchivist** 2022-03-01 02:42 UTC
