### ISSUE TITLE
401 Search Tweet by Query

### ISSUE THREAD

**Issue by 0xTechnician** [JustAnotherArchivist/snscrape#835] opened 2023-04-15 09:17 UTC
### Describe the bug

I'm running a script that uses sns for python (v0.6.2)

I'm encountering 401 errors using  `sntwitter.TwitterSearchScraper(query).get_items()`

Is this related to Twitter public API upgrade that happened tonight?

Thanks

### How to reproduce

for tweet in sntwitter.TwitterSearchScraper(query).get_items():

### Expected behaviour

it should return a 200

### Operating system

Windows 11

### Python version: output of `python3 --version`

3.10.8

### snscrape version: output of `snscrape --version`

0.6.2

### Scraper

TwitterSearchScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

### Log output

`Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=%24TOMO+min_faves%3A3&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe: non-200 status code (401)`

**Comment by Diegozu97** [comment] 2023-04-15 09:20
I am also having the same issue at the moment.

**Comment by zoubidabida** [comment] 2023-04-15 09:20
Actually the error returned by twitter is : 
{"errors":[{"message":"Bad Authentication data","code":215}]}

**Comment by Diegozu97** [comment] 2023-04-15 09:22
I get. 

Errors: non-200 status code (401), non-200 status code (401), non-200 status code (401), non-200 status code (401)

**Comment by porgej** [comment] 2023-04-15 09:42
I am also experiencing the same issue as displayed beneath:

Errors at:
    for i, tweet in enumerate(sntwitter.TwitterSearchScraper(f'{tweet} since:{yday} until:{tday}').get_items()):

**Comment by Yomguithereal** [comment] 2023-04-15 10:05
Related to https://github.com/medialab/minet/issues/682

**Comment by JustAnotherArchivist** [comment] 2023-04-15 10:22
Duplicate of #834

**Closed by JustAnotherArchivist** 2023-04-15 10:22 UTC
Labels: duplicate
