### ISSUE TITLE
How to get only Tweets, and exclude replies?

### ISSUE THREAD

**Issue by satriosadewo** [JustAnotherArchivist/snscrape#451] opened 2022-04-14 16:04 UTC
Hi all,

I have successfully scraped tweets from several accounts with this code (I use Jupiter Notebook)

```
maxTweets = 30
tweets_list1 = []
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:shopeeid').get_items()):
    if i>maxTweets:
        break
    tweets_list1.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.replyCount, tweet.retweetCount, tweet.likeCount, tweet.outlinks, tweet.media, tweet.mentionedUsers])

dff = pd.DataFrame(tweets_list1, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'reply', 'retweet', 'like', 'outlink', 'media', 'mentioned_user'])
```
However, I have a problem when I want to scrape tweets from an account which have very high activity in replying. So, If I scrape 1000 tweets, 950 of them just reply. 
Would you mind helping me to modify my code above, so I can automatically scrape only tweets and exclude the replies?

thank you in advance!

**Comment by JustAnotherArchivist** [comment] 2022-04-14 16:10
Duplicate of #45

**Closed by JustAnotherArchivist** 2022-04-14 16:10 UTC
