### ISSUE TITLE
how to get all number of retweets from specific twitter account?

### ISSUE THREAD

**Issue by shg1998** [JustAnotherArchivist/snscrape#544] opened 2022-09-03 07:34 UTC
Hi, 
how to get all number of retweets from specific twitter account?

**Comment by JustAnotherArchivist** [comment] 2022-09-04 11:16
Duplicate of #83

Accurate numbers would require scraping. If you don't mind the number possibly being *very* wrong, you can run a normal `twitter-user` scrape and subtract the number of results from the `User` object's ` statusesCount` value. This will give you an upper bound on the maximum number of retweets.

**Closed** 2022-09-04 11:16 UTC
Labels: duplicate
