### ISSUE TITLE
Twitter Scraping: get more than the last 9 days' retweets

### ISSUE THREAD

**Issue by royantoine** [JustAnotherArchivist/snscrape#322] opened 2021-12-02 13:50 UTC
Hello,

when using the 'include:nativeretweets' (or 'filter:nativeretweets') in the twitter search, we can only get the retweets from the last 9 past days (so same thing when using snscrape for this purpose). 
Is there any other way to get the username of the people who retweeted tweets mentioning a specific hashtag in the past (beyond the last 9 days)?
Thanks!

**Comment by JustAnotherArchivist** [comment] 2021-12-02 13:56
Duplicate of #83 and #103

**Closed by JustAnotherArchivist** 2021-12-02 13:56 UTC
