### ISSUE TITLE
Scraping Tweets with retweet and favourite counts

### ISSUE THREAD

**Issue by rampager525** [JustAnotherArchivist/snscrape#170] opened 2020-12-16 15:38 UTC
Hi. I have been using snscrape ever since GetoldTweets3 doesn't work. This is the code that I am using now: 

```python
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:jack').get_items()):
    if i>maxTweets:
        break
    tweets_list1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])

# Creating a dataframe from the tweets list above
tweets_df1 = pd.DataFrame(tweets_list1, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])

# Display first 5 entries from dataframe
tweets_df1.head()
```

While scraping the tweets, can I also scrape the retweet and favourite counts into the dataframe?

**Comment by JustAnotherArchivist** [comment] 2020-12-16 16:38
Duplicate of #138

**Closed by JustAnotherArchivist** 2020-12-16 16:38 UTC
