### ISSUE TITLE
Group Doesn't exist.

### ISSUE THREAD

**Issue by Subhan-Zaheer** [JustAnotherArchivist/snscrape#1004] opened 2023-07-04 06:07 UTC
### Describe the bug

I'm trying to scrape a Facebook Group data but couldn't do that as I am facing following error : 
`ScraperException: Code container ID marker not found (does the group exist?)`

### How to reproduce

```python3
import snscrape

# Fetch the Facebook posts
count = 10
for i, post in enumerate(snscrape.modules.facebook.FacebookGroupScraper('instantdata').get_items()):
    if i > count:
        break
```

This is the shortest possible code that causes the error.

### Expected behaviour

```python3
import snscrape

# Fetch the Facebook posts
count = 10
for i, post in enumerate(snscrape.modules.facebook.FacebookGroupScraper('instantdata').get_items()):
    if i > count:
        break
```

This is the code I am using to scrape data and it should return me scraped data.

### Screenshots and recordings

![image](https://github.com/JustAnotherArchivist/snscrape/assets/89686099/12680794-5b52-4842-9df5-af99717384d9)

### Operating system

Windows 11

### Python version: output of `python3 --version`

Python 3.10.11

### snscrape version: output of `snscrape --version`

snscrape 0.7.0.20230622

### Scraper

FacebookGroupScraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by TheTechRobo** [comment] 2023-07-04 13:16
Duplicate of #121?

**Closed as not planned** 2023-07-04 15:17 UTC
Labels: duplicate

**Comment by Subhan-Zaheer** [comment] 2023-07-05 17:59
> Duplicate of #121?

Yes same issue.

**Comment by Subhan-Zaheer** [comment] 2023-07-05 18:00
> > Duplicate of #121?
> 
> Yes same issue.

What should i do now ? is there any way to solve it ?

**Comment by JustAnotherArchivist** [comment] 2023-07-05 18:01
If an issue is open, it means it is not fixed. If a workaround existed, it would be mentioned there.
