### ISSUE TITLE
Snscrape not returning  twitter data from since to until

### ISSUE THREAD

**Issue by ClaireMuriuki** [JustAnotherArchivist/snscrape#564] opened 2022-10-06 17:59 UTC
I am trying to scrape Twitter data but snscrape returns data of the date just before the until date, in other cases data for the since date only . For instance, I queried  ('bitcoin since:2022-01-01 until:2022-09-13'), in this case, it only returns data for 2022-09-12 only.
check screenshots.

![Screenshot (57)](https://user-images.githubusercontent.com/87611034/194384051-393ccb42-6be5-434c-9af6-972c36b32c1e.png)
![Screenshot (58)](https://user-images.githubusercontent.com/87611034/194384118-4db209ae-c143-4b3f-92c4-6677b856f441.png)
 2022-09-13

**Comment by JustAnotherArchivist** [comment] 2022-10-08 17:16
Yes, Twitter's `until` filter is exclusive. (Think of it as 'before' instead.)
You're only getting tweets from 2022-09-12 because there are more than 5001 results.

Duplicate of #191 and others

**Closed by JustAnotherArchivist** 2022-10-08 17:16 UTC
