### ISSUE TITLE
List of Likers OR Retweeters of a specific tweet.

### ISSUE THREAD

**Issue by sufyanhamid** [JustAnotherArchivist/snscrape#240] opened 2021-06-15 21:32 UTC
Hi @JustAnotherArchivist  !!

I have a question regarding twitter's search query. Is there a way to get the list of users who like/ Retweet a specific post ? Hopefully you will understand my query and help me to do this in a right way.

Thanks in advance :)

**Comment by JustAnotherArchivist** [comment] 2021-06-15 22:02
Duplicate of #103

**Closed by JustAnotherArchivist** 2021-06-15 22:02 UTC
