### ISSUE TITLE
Twitter: raise ValueError('missing media')

### ISSUE THREAD

**Issue by zhbbbbbb** [JustAnotherArchivist/snscrape#470] opened 2022-05-11 00:50 UTC
Hi, I used the sntwitter module and for some dates I get a ValueError('missing media'). The generator seems to stop once this error is raised and there is no way to continue the generator. I was using list comprehension to 

The code I have:
tweet_criteria = f"{['bitcoin', 'BTC']} since:{'2022-02-20'} until:{'2022-02-21'}"
tweets_list = [[tweet.date, tweet.user.username, tweet.content] for tweet in tweets] # <- raised the missing media error

What's causing this error and is there a way to get past this error? Thanks a lot in advance.

**Comment by TheTechRobo** [comment] 2022-05-11 00:58
Uh, this shouldn't happen. https://github.com/JustAnotherArchivist/snscrape/blob/ed3ea944d177157d688786470c8369198b0ce8ce/snscrape/modules/twitter.py#L324

Do you have any idea what tweet it's failing on?

**Comment by JustAnotherArchivist** [comment] 2022-05-11 01:39
Confirmed, happens on tweet 1489690131174813700, haven't looked into it closer yet.

**Comment by zhbbbbbb** [comment] 2022-05-11 01:45
I tried my same code on Google Colab and it didn't run into this error. But Google Colab was running version 0.3.4

**Comment by JustAnotherArchivist** [comment] 2022-05-11 01:46
Yeah, this is coming from the recently added card extraction, which is currently only available in the dev version.

**Comment by openandclose** [comment] 2022-05-30 04:10
> Confirmed, happens on tweet 1489690131174813700, haven't looked into it closer yet.

how to query 1489690131174813700 itself
in web browser and snscrape?

**Comment by JustAnotherArchivist** [comment] 2022-05-30 04:12
https://twitter.com/i/web/status/1489690131174813700
`snscrape twitter-tweet 1489690131174813700`

**Comment by openandclose** [comment] 2022-05-30 04:29
Sorry again,

How to reproduce that ``1489690131174813700`` raises ``ValueError``?

**Comment by JustAnotherArchivist** [comment] 2022-05-30 05:18
Apparently it doesn't anymore. I guess it was fixed on Twitter's side since. I still have a dump file from when it did though, and it looks like Twitter didn't return the app icon for iOS at the time.

If anyone sees this happen again, please comment and I'll reopen. Otherwise, I'll consider this a transient bug on Twitter's side.

**Comment by openandclose** [comment] 2022-05-30 14:35
Just for the record...

I had the same error about 10 hours ago.
But somehow the error disappeared about 8 hours ago or so (and now).

The URL is:
https://twitter.com/vgr/status/1484404514295730177
Or its quoted tweet:
https://twitter.com/get_headway/status/1477753186551312386
(looks similar to ``1489690131174813700``)

I don't think this issue should be reopened, since it's fixed now.

I don't have dumps, just error message.

```
Traceback (most recent call last):

  [from TwitterSearchScraper ...]

  File "[...]snscrape/snscrape/modules/twitter.py", line 1440, in get_items
    yield from self._v2_timeline_instructions_to_tweets(obj)
  File "[...]snscrape/snscrape/modules/twitter.py", line 797, in _v2_timeline_instructions_to_tweets
    yield from self._v2_instruction_tweet_entry_to_tweet(entry['entryId'], entry['content'], obj)
  File "[...]snscrape/snscrape/modules/twitter.py", line 820, in _v2_instruction_tweet_entry_to_tweet
    yield self._tweet_to_tweet(tweet, obj)
  File "[...]snscrape/snscrape/modules/twitter.py", line 1260, in _tweet_to_tweet
    kwargs['quotedTweet'] = self._tweet_to_tweet(obj['globalObjects']['tweets'][tweet['quoted_status_id_str']], obj)
  File "[...]snscrape/snscrape/modules/twitter.py", line 1262, in _tweet_to_tweet
    kwargs['card'] = self._make_card(tweet['card'], _TwitterAPIType.V2, self._get_tweet_id(tweet))
  File "[...]snscrape/snscrape/modules/twitter.py", line 1250, in _make_card
    return UnifiedCard(**kwargs)
  File "<string>", line 10, in __init__
  File "[...]snscrape/snscrape/modules/twitter.py", line 338, in __post_init__
    raise ValueError('missing media')
ValueError: missing media
```

**Comment by openandclose** [comment] 2022-05-30 14:40
(snscrape version is newest (530f4fa)).

**Comment by oklebs** [comment] 2022-08-13 09:47
Hello, I am facing the same proble where I get ValueError: missing media. The generator seems to stop once this error is raised and there is no way to continue the generator.  However, the query works on other queries like '(clean energy) OR (#cleanenergy)'

My code is as follows:

```
tweets_list_ge_eu = []

max_tweets = 5000
search_text = '(green energy) OR (#greenenergy)'
tweets_since = '2021-06-01'
tweets_until = '2022-06-01'
lang = 'en'
loc_near = 'Europe'

for i,tweet in enumerate(sntwitter.TwitterSearchScraper('{0} since:{1} until:{2} lang:{3} near:{4}'.format(search_text, tweets_since, tweets_until, lang, loc_near)).get_items()):
    if i > max_tweets:
        break
    tweets_list_ge_eu.append([tweet.date, tweet.rawContent, tweet.hashtags, tweet.lang, tweet.user.location, tweet.coordinates, tweet.place])
    
tweets_df_ge_eu = pd.DataFrame(tweets_list_ge_eu, columns=['date_time', 'original_content', 'hashtags', 'language', 'user_location', 'coord', 'place'])
tweets_df_ge_eu

```

May I know what's causing this error and whether there is a way to get past this error? Thanks a lot in advance.

**Comment by JustAnotherArchivist** [comment] 2022-08-13 21:16
Currently reproducible with tweet 1463163881006813196. Same as before, it references an app icon medium 4_1558225980539510784, but there is no such medium in the response.
The app is pretty old already, released in November. Maybe Twitter's cache of the app icon expired or something weird like that, and their handling of that situation is broken. I'll just drop the app icon if it isn't actually in the response (and emit a warning).

**Closed** 2022-08-13 21:18 UTC
Labels: bug, wontfix, module:twitter, upstream

**Comment by Ahmed-Sh** [comment] 2023-02-04 23:36
Hello,
I got the same problem today.
my code:
```
'''
def tweet_scrap(user, date1, date2):
    # Created a list to append some tweets attributes
    attributes_container = []
    # Using TwitterSearchScraper to scrape data and append tweets to list
    for tweet in sntwitter.TwitterSearchScraper(f'from:{user} since:{date1} until:{date2}').get_items():
        attributes_container.append([tweet.date, tweet.sourceLabel, tweet.rawContent])
        
    # Creating a dataframe from the tweets list above
    df = pd.DataFrame(attributes_container, columns=["Date_Created", "Source_of_Tweet", "Tweets"])
    file_n = user[1:]
    return df, file_n

tweets_from = '@snbalahli'

start_date = '2022-09-01'
end_date = '2023-01-01'

# scraping data 
df, file_name = tweet_scrap(i, start_date, end_date)
# writing csv file
df.to_csv(file_name + '3' + '.csv', index=False)
'''
```
with this error:
ValueError                                Traceback (most recent call last)
Cell In[36], line 7
      4 end_date = '2023-01-01'
      6 # scraping data 
----> 7 df, file_name = tweet_scrap(i, start_date, end_date)
      8 # writing csv file
      9 df.to_csv(file_name + '3' + '.csv', index=False)

Cell In[31], line 16, in tweet_scrap(user, date1, date2)
     14 attributes_container = []
     15 # Using TwitterSearchScraper to scrape data and append tweets to list
---> 16 for tweet in sntwitter.TwitterSearchScraper(f'from:{user} since:{date1} until:{date2}').get_items():
     17     attributes_container.append([tweet.date, tweet.sourceLabel, tweet.rawContent])
     19 # Creating a dataframe from the tweets list above

File G:\Anaconda3\envs\tenv\lib\site-packages\snscrape\modules\twitter.py:1547, in TwitterSearchScraper.get_items(self)
   1544 	del paginationParams['tweet_search_mode']
   1546 for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', _TwitterAPIType.V2, params, paginationParams, cursor = self._cursor):
-> 1547 	yield from self._v2_timeline_instructions_to_tweets(obj)

File G:\Anaconda3\envs\tenv\lib\site-packages\snscrape\modules\twitter.py:853, in _TwitterAPIScraper._v2_timeline_instructions_to_tweets(self, obj, includeConversationThreads)
    851 for entry in entries:
    852 	if entry['entryId'].startswith('sq-I-t-') or entry['entryId'].startswith('tweet-'):
--> 853 		yield from self._v2_instruction_tweet_entry_to_tweet(entry['entryId'], entry['content'], obj)
    854 	elif includeConversationThreads and entry['entryId'].startswith('conversationThread-') and not entry['entryId'].endswith('-show_more_cursor'):
    855 		for item in entry['content']['timelineModule']['items']:

File G:\Anaconda3\envs\tenv\lib\site-packages\snscrape\modules\twitter.py:876, in _TwitterAPIScraper._v2_instruction_tweet_entry_to_tweet(self, entryId, entry, obj)
    874 else:
    875 	raise snscrape.base.ScraperException(f'Unable to handle entry {entryId!r}')
--> 876 yield self._tweet_to_tweet(tweet, obj)

File G:\Anaconda3\envs\tenv\lib\site-packages\snscrape\modules\twitter.py:1348, in _TwitterAPIScraper._tweet_to_tweet(self, tweet, obj)
   1346 	kwargs['quotedTweet'] = self._tweet_to_tweet(obj['globalObjects']['tweets'][tweet['quoted_status_id_str']], obj)
   1347 if 'card' in tweet:
-> 1348 	kwargs['card'] = self._make_card(tweet['card'], _TwitterAPIType.V2, self._get_tweet_id(tweet))
   1349 if 'ext_views' in tweet and 'count' in tweet['ext_views']:
   1350 	kwargs['viewCount'] = int(tweet['ext_views']['count'])

File G:\Anaconda3\envs\tenv\lib\site-packages\snscrape\modules\twitter.py:1329, in _TwitterAPIScraper._make_card(self, card, apiType, tweetId)
   1326 			_logger.warning(f'Unsupported unified_card layout type on tweet {tweetId}: {o["layout"]["type"]!r}')
   1327 			return
-> 1329 	return UnifiedCard(**kwargs)
   1331 _logger.warning(f'Unsupported card type on tweet {tweetId}: {cardName!r}')

File <string>:11, in __init__(self, componentObjects, destinations, media, apps, components, swipeableLayoutSlides, collectionLayoutSlides, type)

File G:\Anaconda3\envs\tenv\lib\site-packages\snscrape\modules\twitter.py:350, in UnifiedCard.__post_init__(self)
    348 mediaKeys.extend(a.iconMediumKey for l in (self.apps.values() if self.apps is not None else []) for a in l if a.iconMediumKey is not None)
    349 if any(k not in self.media for k in mediaKeys):
--> 350 	raise ValueError('missing media')
    351 if any(c.appKey not in self.apps for c in self.componentObjects.values() if hasattr(c, 'appKey')):
    352 	raise ValueError('missing apps')

ValueError: missing media

**Comment by TheTechRobo** [comment] 2023-02-04 23:37
Please file a complete bug report. https://github.com/JustAnotherArchivist/snscrape/issues/new?assignees=&labels=bug&template=bug_report.yml
