### ISSUE TITLE
Scraping retweets? 

### ISSUE THREAD

**Issue by lithium135** [JustAnotherArchivist/snscrape#150] opened 2020-11-02 00:09 UTC
The command `snscrape --jsonl --since 2020-10-01 twitter-user @BarackObama` gives tweets posted by the account BarackObama since the date specified. Is there a way to scrape all retweets by this account as well (i.e. tweets Obama 'shares' to his followers)?

**Comment by JustAnotherArchivist** [comment] 2020-11-02 16:00
Duplicate of #83

**Closed by JustAnotherArchivist** 2020-11-02 16:00 UTC
