### ISSUE TITLE
A potential solution for recent " ScraperException: 4 requests to ....." bug

### ISSUE THREAD

**Issue by msamancioglu** [JustAnotherArchivist/snscrape#659] opened 2023-01-12 13:25 UTC
Hi, because twitter removed "Top" tab, some params/settings of requests become invalid. Removing following settings worked for me (in the twitter.py)

1. remove ('f': 'live') from baseUrl:
super().init(baseUrl = 'https://twitter.com/search?src=typed_query&' + urllib.parse.urlencode({'f': 'live', 'lang': 'en', 'q': query, 'sr

2. remove ('tweet_search_mode': 'live') from paginationParams

What do you think @JustAnotherArchivist 

ps: I had to place here as original topic locked

**Comment by msamancioglu** [comment] 2023-01-12 13:49
without any search param, try this :

    from snscrape.modules.twitter import TwitterSearchScraper 
    maxTweets = 10
    tweets_list = []    
    for i,tweet in enumerate(TwitterSearchScraper('elon musk').get_items()):        
        if i>maxTweets:
            break
        tweets_list1.append({
            "date": tweet.date,
            "id":tweet.id,
            "content":tweet.content,
            "username":tweet.user.username
            })

**Comment by msamancioglu** [comment] 2023-01-12 13:51
here is what I got :
{
"tweets": [
{
"date": "2023-01-12T11:22:02+00:00",
"id": 1613496520984367000,
"content": "Imagine having Elon Musk as your teacher 😃 https://t.co/Agix8Thpit",
"username": "MattWallace888"
},
{
"date": "2023-01-12T02:47:46+00:00",
"id": 1613367103075061800,
"content": "Cybertruck, Roadster, Semi - Tesla’s future is bright. Tesla will kill it in 2023 and beyond. @elonmusk https://t.co/UyecCbsCly",
"username": "EvasTeslaSPlaid"
},
{
"date": "2023-01-12T04:19:23+00:00",
"id": 1613390155536023600,
"content": ".@elonmusk Is the Tesla Roadster still on target for delivery in 2023? https://t.co/lntRXjA01Q",
"username": "EvasTeslaSPlaid"
},
{
"date": "2023-01-12T08:07:41+00:00",
"id": 1613447611222032400,
"content": "SpaceX is literally making science fiction a reality. Landing of rockets were just depicted in movies before SpaceX came along and implemented them in real life 🤯 @elonmusk \n\n https://t.co/hA5KDObRei",
"username": "PPathole"
},

**Comment by nobody613** [comment] 2023-01-12 14:02
first : THANKS  about you time 
did you use with a basic barrer provides by code , i mean ;
_API_AUTHORIZATION_HEADER = 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs=1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA'

 ?

**Comment by NeilCutter** [comment] 2023-01-12 14:12
> without any extra param, try this :
> 
> ```
> from snscrape.modules.twitter import TwitterSearchScraper 
> maxTweets = 10
> tweets_list = []    
> for i,tweet in enumerate(TwitterSearchScraper('elon musk').get_items()):        
>     if i>maxTweets:
>         break
>     tweets_list.append({
>         "date": tweet.date,
>         "id":tweet.id,
>         "content":tweet.content,
>         "username":tweet.user.username
>         })
> ```

This still not working on my end. :<

**Comment by Idan-Garay** [comment] 2023-01-12 14:17
I tried in colab. It also doesn't work on my end

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/47768819/212090027-e5a98a93-7722-41f4-9a57-c03e06bdc93d.png">

**Comment by nobody613** [comment] 2023-01-12 14:25
OK, I tried all the options - and it didn't work

I have only one guess:
1. You introduced the changes in SSL
2. You use LINUX
3. It also works when you use the basic barrer

I'm right ?
If so - I understand what is happening here

> with this search 'elon musk lang:ar near:iraq'
> 
> getting following response:
> 
> { "date": "2023-01-12T13:37:16+00:00", "id": 1613530551520051200, "content": "والله دكتور @ElonMusk \nجدا شخص منافق ودجال منذ استلامه تويتر ولا نعرف ماذا يحدث بالتغريدات https://t.co/3mWeElIbam", "username": "mazin_shubber" }, { "date": "2023-01-04T09:27:41+00:00", "id": 1610568641057067000, "content": "أكبر خسارة لشخص في التاريخ.. "ماسك" يخسر 212 مليار دولار من ثروته خلال 13 شهرا\n\n#عراق_24 #إيلون_ماسك #العالم \n@elonmusk https://t.co/Cz7jJaFgIS", "username": "IRAQ24HD" }, { "date": "2023-01-04T10:56:58+00:00", "id": 1610591108626583600, "content": "رفع دعوى قضائية ضد #ايلون_ماسك @ElonMusk بسبب عدم تسديده ايجار احدى بنايات شركة #تويتر @twitter .\n\n#العالم_بعيون_رقمية\n#مركز_الاعلام_الرقمي DMC https://t.co/3EmIVOp96w", "username": "iraqDMC" }, { "date": "2023-01-02T15:05:05+00:00", "id": 1609928775747178500, "content": "@Maans1975 @BAldhrany @tgwear25 @Ldovyka @oh_laa_laa @500K_______ @ho88_sh @satansradio666 @Dada80131289 @SaulHHHz @kathe62567628 @ArshadShamim8 @WidzDj @MalevolaKR @DivinoCRF @Iva_LaRosa @yonacadirolaOK @YolydeSandoval1 @1firj @Eles26 @Javier9_12 @Magdale_Aguilar @DyeLLEn_QuEEn @Alus9fy @ElonMusk @rq_msha @AsltanataZri9i @anesmansory @yemeniarkia @ymniija @75suhair @AaiatAna @_0M01 @_i1ig @Zo3nT @cute_priyam13 @FLOWI112 @SYMeetali @BeingVibhaSingh @yogi_jaiho @iCareReforms @Vverma99971 @RRR000000001 @newstimeagra99 @bikki_pandit @101_rangel @Bhupend154 @Hira_awa مساؤكم بكل خير وبركه \n🌺🌺🌺🌺🌺", "username": "faiez_nj" },



OK, I tried all the options - and it didn't work

I have only one guess:
1. You introduced the changes in SSL
2. You use LINUX
3. It also works when you use the basic barrer

I'm right ?
If so - I understand what is happening here

**Comment by msamancioglu** [comment] 2023-01-12 14:39
Sorry for insufficient details, my bad. Let me clear,

1. applied SSL changes suggested here:
https://github.com/JustAnotherArchivist/snscrape/issues/648#issuecomment-1379502032
2. using "Ubuntu 22.04.1 LTS"
3. dindn`t do any change regarding authentication/bearer

**Comment by 0bmay** [comment] 2023-01-12 15:10
@msamancioglu I  still see a Top tab when searching and the most important item for your fix is the SSL Cipher fix - or your item 1.  This thread is kind of misleading in that respect.

**Comment by msamancioglu** [comment] 2023-01-12 15:33
@0bmay firstly, Top tab is only available when you are logged in.
secondly, problem persisted on my side even after applying SSL fix, so I had to dig deeper.

**Comment by 0bmay** [comment] 2023-01-12 15:36
@msamancioglu i never log into twitter and after making a search I see the top tab. ¯\_(ツ)_/¯ 

As for the ssl fix not working, you may be right. I believe I'm running an older version.. 1.1.1 on macOS.

**Comment by JustAnotherArchivist** [comment] 2023-01-12 16:00
The 'top' tab still exists for unauth'd users. This is just another duplicate of #634.

**Closed by JustAnotherArchivist** 2023-01-12 16:00 UTC
Labels: duplicate
