### ISSUE TITLE
Unable to find guest token even after upgrade to latest version

### ISSUE THREAD

**Issue by nate-ellis** [JustAnotherArchivist/snscrape#361] opened 2022-01-16 17:41 UTC
I've read the past comments of persons having the same issue. I've uninstalled, reinstalled, and upgraded. Still receiving:

"ScraperException: Unable to find guest token"

Any thoughts?

**Comment by JustAnotherArchivist** [comment] 2022-01-16 17:45
You are not using the latest version of snscrape. Make sure you have Python 3.8 or higher, else pip will silently ignore the newer versions.

Duplicate of #347

**Closed by JustAnotherArchivist** 2022-01-16 17:45 UTC
