### ISSUE TITLE
Geographical limitations

### ISSUE THREAD

**Issue by Barbz2** [JustAnotherArchivist/snscrape#332] opened 2021-12-18 16:10 UTC
I was wondering if there is a way to limit the geolocation of tweet extraction? I wanted to focus solely on England but have not been able to find any commands for this.

**Comment by lahdjirayhan** [comment] 2021-12-18 17:36
It looks like what you ask is a possible duplicate of #271 or #145. Please take a look at those.

**Closed** 2021-12-21 22:00 UTC
Labels: duplicate
