### ISSUE TITLE
GUI support for inexperienced users

### ISSUE THREAD

**Issue by upintheairsheep** [JustAnotherArchivist/snscrape#337] opened 2021-12-30 05:11 UTC
To attract a larger audience of archivists that are either not familiar with the command line, or for people who thinks it is a pain in the ass to setup phyton, use this tool to make a gui for the lesser experienced people.
https://github.com/chriskiehl/Gooey

**Comment by JustAnotherArchivist** [comment] 2021-12-30 05:12
Duplicate of #14

**Closed by JustAnotherArchivist** 2021-12-30 05:12 UTC
