### ISSUE TITLE
instagram hashtag error

### ISSUE THREAD

**Issue by Xamk-DataLAB** [JustAnotherArchivist/snscrape#202] opened 2021-03-17 20:23 UTC
`snscrape instagram-hashtag ` seems to fail with ScraperException: Redirected to login page every time using python 3.8.5 and snscrape version 0.3.5.dev91+gfdc33d0. I think this was workin like a week ago..locations and profiles seem to work. Traceback copied below:

> Traceback (most recent call last):
>   File "/usr/local/anaconda3/bin/snscrape", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/anaconda3/lib/python3.8/site-packages/snscrape/_cli.py", line 270, in main
>     for i, item in enumerate(scraper.get_items(), start = 1):
>   File "/usr/local/anaconda3/lib/python3.8/site-packages/snscrape/modules/instagram.py", line 137, in get_items
>     r = self._initial_page()
>   File "/usr/local/anaconda3/lib/python3.8/site-packages/snscrape/modules/instagram.py", line 111, in _initial_page
>     raise snscrape.base.ScraperException('Redirected to login page')
> snscrape.base.ScraperException: Redirected to login page

**Comment by JustAnotherArchivist** [comment] 2021-03-17 21:12
That means your IP got banned by Instagram.

Duplicate of #165

**Closed by JustAnotherArchivist** 2021-03-17 21:12 UTC
Labels: duplicate
