### ISSUE TITLE
Twitter Rate Limits?

### ISSUE THREAD

**Issue by koufopoulosf** [JustAnotherArchivist/snscrape#551] opened 2022-09-13 09:46 UTC
Hello @JustAnotherArchivist,

I would like to ask you a few general questions regarding the twitter module.

1. I guess the tweets are using this API:

`_API_AUTHORIZATION_HEADER = 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs=1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA'`

So what's the max/total number of tweets that can be consumed using the above API (per month?) ?

2. Can I replace this one with any other APIs without causing issues - or does it require to be used a specific one like a professor's/researcher's API that matches with the functionality of the code?

3. How does this code surpass the twitters rate limits? What am I missing? I mean it's downloading easily thousands of tweets. Should I be aware of any restrictions while using this script for twitter?

Thank you very much for your valuable time and I keep looking forward for your reply.

Best Regards,

koufopoulosf

**Comment by Ashoka74** [comment] 2022-09-13 10:18
Hi @koufopoulosf ;

Using the Twitter API, the rate limits depend on which service you are using (recent_search, history_search, streaming..) and which package you applied to (sandbox, premium, academic..)

You can have an overview of the rate_limits on this page. For instance; one request accounts for 500 tweets with a Premium subscription, but only 100 tweets with a sandbox subscription.
https://developer.twitter.com/en/docs/twitter-api/rate-limits

For this package, I suppose there are no restrictions for the search or user_timeline. 
You can check this tutorial for python implementation:

https://www.freecodecamp.org/news/python-web-scraping-tutorial/

**Comment by koufopoulosf** [comment] 2022-09-13 10:49
Hi @Ashoka74,

Thank you very much for your detailed reply.

That's what I am wondering, why there are no restriction limits using snscrape for twitter? How is that possible?

And if it's a kind of "bug" that twitter has missed, how are we sure that this will continue to keep working in the future?

**Comment by koufopoulosf** [comment] 2022-09-13 12:55
@TheTechRobo,

Thank you very much for your valuable reply as well. Your answer triggers more questions.

> You can change it, but you'd need to change all the code that depends on the current API.

I mostly asked this question in case I hit the limit of this API, to make use of another API. However if changing the whole code is needed, I guess that wouldn't be quite useful. Are the changes required somewhere documented though?

> I personally have not run into any issues, except KeyError: 'result' which I suspect might be rate limiting since it can be resolved by rerunning the scrape. However, I haven't used snscrape in a good while.

Still, how is it possible though to scrape unlimited tweets by the time Twitter seeks to force a pricing on them or use specific rate limits? That's what I can't figure out and as I said, if that's a kind of "bug" that twitter has missed, how are we sure that this will continue to keep working in the future?

**Comment by JustAnotherArchivist** [comment] 2022-09-13 19:28
Duplicate of #385 and others. I do not intend to ever document the details of their rate limiting and workarounds. You won't get any guarantees here anyway. Be glad that it works now, and use it until they make it hard enough that it can't work anymore...

**Closed by JustAnotherArchivist** 2022-09-13 19:28 UTC

**Comment by koufopoulosf** [comment] 2022-09-14 07:22
@JustAnotherArchivist Thank you!
