### ISSUE TITLE
AttributeError: 'FileFinder' object has no attribute 'find_module'

### ISSUE THREAD

**Issue by xts-bit** [JustAnotherArchivist/snscrape#1038] opened 2023-12-13 14:59 UTC
### Describe the bug

I get this error when i install the package and try to run my code. the error is "AttributeError: 'FileFinder' object has no attribute 'find_module'" 

Anyone help please ,
```

import snscrape.modules.twitter as sntwitter
import pandas as pd

username = "elonmusk"

tweets_list = []

for i, tweet in enumerate(sntwitter.TwitterSearchScraper('from:'+username).get_items()):
    if i >= 100:  
        break
    tweets_list.append([tweet.date, tweet.id, tweet.content, tweet.url])
tweets_df = pd.DataFrame(tweets_list, columns=['Datetime', 'Tweet Id', 'Text', 'URL'])

print(tweets_df)
```

### How to reproduce

python3 index.py

### Expected behaviour

It should get all tweets by elon musk

### Operating system

MacOS

### Python version: output of `python3 --version`

Python 3.12.0

### snscrape version: output of `snscrape --version`

I again get this error AttributeError: 'FileFinder' object has no attribute 'find_module'

### Scraper

twitter 

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

**Comment by JustAnotherArchivist** [comment] 2023-12-16 08:27
Duplicate of #782, but Twitter scraping won't work currently even after that's resolved (#996).

**Closed as not planned by JustAnotherArchivist** 2023-12-16 08:27 UTC
Labels: duplicate

**Comment by xts-bit** [comment] 2023-12-16 09:19
@JustAnotherArchivist So when will it fiX?

**Comment by tangruixun** [comment] 2024-03-04 06:57
How to fix this????????????

**Comment by cheerful-capuchin** [comment] 2025-05-29 13:17
> How to fix this????????????

1. Download the source `git clone https://github.com/JustAnotherArchivist/snscrape.git`
2. patch the file [snscrape/modules/__init__.py](https://github.com/JustAnotherArchivist/snscrape/blob/master/snscrape/modules/__init__.py) with
```python
from . import facebook
from . import instagram
from . import mastodon
from . import reddit
from . import telegram
from . import twitter
from . import vkontakte
from . import weibo

__all__ = [
    'facebook',
    'instagram',
    'mastodon',
    'reddit',
    'telegram',
    'twitter',
    'vkontakte',
    'weibo',
]
```

3. in the root of the repo do `uv pip install -e .` (uv is https://github.com/astral-sh/uv)
4. `uv run snscrape --help`

if it works -> you can use the tool
