### ISSUE TITLE
some specific twitter_id cannot used by sntwitter.TwitterUserScraper

### ISSUE THREAD

**Issue by nathan1505** [JustAnotherArchivist/snscrape#511] opened 2022-07-08 03:18 UTC
Hi! I try to get the profile of some twitter users by `TwitterUserScraper`.  This is what I type below:

```python
import snscrape.modules.twitter as sntwitter

profile = []
for tweet in sntwitter.TwitterUserScraper("RTFKTstudios").get_items():
    profile.append([tweet.user.id, tweet.user.username, tweet.user.displayname, tweet.user.followersCount, tweet.user.profileImageUrl, tweet.user.created])
    break

print(profile)
```

It returns an empty array after that. I tried to replace the user id with `larvalabs` and still get an empty return.  However, the other  id works fine. Is there any reason why the two ids fail to return data?

**Comment by JustAnotherArchivist** [comment] 2022-07-08 11:38
Duplicate of #4

**Closed by JustAnotherArchivist** 2022-07-08 11:38 UTC
