### ISSUE TITLE
4 requests to ... failed giving up

### ISSUE THREAD

**Issue by Pii-R** [JustAnotherArchivist/snscrape#486] opened 2022-06-04 12:27 UTC
I recently have some trouble to run snscrape for twitter search.

Here is the command I want to run : 

```
snscrape --jsonl --max-results 5 twitter-search '(from:TopAchat, OR from:CdiscountGaming, OR from:HypergamesA, OR from:karmaaOfficiel, OR from:XboxOrNot, OR from:AccLocck, OR from:RazerFrance, OR from:ESL_PwnZ, OR from:insertcoinFR, OR from:Truffaut, OR from:SteelSeriesFR, OR from:TMThrustmaster, OR from:TheGuill84, OR from:seagategaming, OR from:GUNNARFRANCE, OR from:AzodPromoter, OR from:PlayStationFR, OR from:FRhardware, OR from:coolermasterfr, OR from:materielnet, OR from:Desastre_Show, OR from:OMENbyHP_fr, OR from:phenixfr) #concours exclude:replies'
```
Sometimes it crashes sometimes it runs. Here the error message that I get:
```
2022-06-04 14:21:52.471  ERROR  snscrape.base  Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3ATopAchat%2C+OR+from%3ACdiscountGaming%2C+OR+from%3AHypergamesA%2C+OR+from%3AkarmaaOfficiel%2C+OR+from%3AXboxOrNot%2C+OR+from%3AAccLocck%2C+OR+from%3ARazerFrance%2C+OR+from%3AESL_PwnZ%2C+OR+from%3AinsertcoinFR%2C+OR+from%3ATruffaut%2C+OR+from%3ASteelSeriesFR%2C+OR+from%3ATMThrustmaster%2C+OR+from%3ATheGuill84%2C+OR+from%3Aseagategaming%2C+OR+from%3AGUNNARFRANCE%2C+OR+from%3AAzodPromoter%2C+OR+from%3APlayStationFR%2C+OR+from%3AFRhardware%2C+OR+from%3Acoolermasterfr%2C+OR+from%3Amaterielnet%2C+OR+from%3ADesastre_Show%2C+OR+from%3AOMENbyHP_fr%2C+OR+from%3Aphenixfr%29+%23concours+exclude%3Areplies&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: non-200 status code
2022-06-04 14:21:52.471  CRITICAL  snscrape.base  4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3ATopAchat%2C+OR+from%3ACdiscountGaming%2C+OR+from%3AHypergamesA%2C+OR+from%3AkarmaaOfficiel%2C+OR+from%3AXboxOrNot%2C+OR+from%3AAccLocck%2C+OR+from%3ARazerFrance%2C+OR+from%3AESL_PwnZ%2C+OR+from%3AinsertcoinFR%2C+OR+from%3ATruffaut%2C+OR+from%3ASteelSeriesFR%2C+OR+from%3ATMThrustmaster%2C+OR+from%3ATheGuill84%2C+OR+from%3Aseagategaming%2C+OR+from%3AGUNNARFRANCE%2C+OR+from%3AAzodPromoter%2C+OR+from%3APlayStationFR%2C+OR+from%3AFRhardware%2C+OR+from%3Acoolermasterfr%2C+OR+from%3Amaterielnet%2C+OR+from%3ADesastre_Show%2C+OR+from%3AOMENbyHP_fr%2C+OR+from%3Aphenixfr%29+%23concours+exclude%3Areplies&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.
2022-06-04 14:21:52.487  CRITICAL  snscrape._cli  Dumped stack and locals to /tmp/snscrape_locals_t9u4j_sa
Traceback (most recent call last):
  File "/home/pierre/Documents/projects/giveaway_bot/.venv/bin/snscrape", line 8, in <module>
    sys.exit(main())
  File "/home/pierre/Documents/projects/giveaway_bot/.venv/lib/python3.10/site-packages/snscrape/_cli.py", line 308, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/home/pierre/Documents/projects/giveaway_bot/.venv/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 680, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams, cursor = self._cursor):
  File "/home/pierre/Documents/projects/giveaway_bot/.venv/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 369, in _iter_api_data
    obj = self._get_api_data(endpoint, reqParams)
  File "/home/pierre/Documents/projects/giveaway_bot/.venv/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 339, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
  File "/home/pierre/Documents/projects/giveaway_bot/.venv/lib/python3.10/site-packages/snscrape/base.py", line 216, in _get
    return self._request('GET', *args, **kwargs)
  File "/home/pierre/Documents/projects/giveaway_bot/.venv/lib/python3.10/site-packages/snscrape/base.py", line 212, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3ATopAchat%2C+OR+from%3ACdiscountGaming%2C+OR+from%3AHypergamesA%2C+OR+from%3AkarmaaOfficiel%2C+OR+from%3AXboxOrNot%2C+OR+from%3AAccLocck%2C+OR+from%3ARazerFrance%2C+OR+from%3AESL_PwnZ%2C+OR+from%3AinsertcoinFR%2C+OR+from%3ATruffaut%2C+OR+from%3ASteelSeriesFR%2C+OR+from%3ATMThrustmaster%2C+OR+from%3ATheGuill84%2C+OR+from%3Aseagategaming%2C+OR+from%3AGUNNARFRANCE%2C+OR+from%3AAzodPromoter%2C+OR+from%3APlayStationFR%2C+OR+from%3AFRhardware%2C+OR+from%3Acoolermasterfr%2C+OR+from%3Amaterielnet%2C+OR+from%3ADesastre_Show%2C+OR+from%3AOMENbyHP_fr%2C+OR+from%3Aphenixfr%29+%23concours+exclude%3Areplies&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.`
```

Am I missing something in the command syntax ? I can´t find where does the error come from.

Thanks

**Comment by TheTechRobo** [comment] 2022-06-04 20:43
That's a lot of OR queries. Removing some fixes this, so this is probably a duplicate of #211

**Comment by JustAnotherArchivist** [comment] 2022-06-05 03:35
Yep, duplicate of #211. The query string is too long. If you remove the commas, it fits into the limit by a few characters.

**Closed by JustAnotherArchivist** 2022-06-05 03:35 UTC

**Comment by Pii-R** [comment] 2022-06-05 08:16
Great, thanks for this quick response and sorry for duplicate.
