### ISSUE TITLE
KeyError: 'tcooutlinks'

### ISSUE THREAD

**Issue by Afefa** [JustAnotherArchivist/snscrape#598] opened 2022-11-28 00:07 UTC
I used snscrape for twitter-search via CLI, it worked good and scraped as much tweets as I asked.  However, I do not know if there are any arguments that could be used to specify the location of the search using CLI commands. Or Are there any tweeter scraper for location?

 

Moreover, when I used snscrape with python wrapper, I could specify the location but I faced this problem:

My Code

```python3
Jtweets_list = []
Jloc = '21.492500, 39.177570, 10km'
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('"" geocode:"{}"'.format(Jloc)).get_items()):
    if i>3000:
        break
    Jtweets_list.append([tweet.user.username, tweet.user.location,tweet.content, tweet.id , tweet.date])
    
# Creating a dataframe from the tweets list above
Jtweets_df = pd.DataFrame(Jtweets_list, columns=['userName', 'userLocation', 'content', 'id', 'date'])
```

Error:

```python traceback
runfile('C:/Users/aafef/OneDrive/Desktop/Afefa_PhD/Coding/Python Learning/snscrape/snscrapeWithpythonCode.py', wdir='C:/Users/aafef/OneDrive/Desktop/Afefa_PhD/Coding/Python Learning/snscrape')
Traceback (most recent call last):

  File "C:\Users\aafef\OneDrive\Desktop\Afefa_PhD\Coding\Python Learning\snscrape\snscrapeWithpythonCode.py", line 61, in <module>
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper('"" geocode:"{}"'.format(Jloc)).get_items()):

  File "C:\Users\aafef\anaconda3\lib\site-packages\snscrape\modules\twitter.py", line 810, in get_items
    yield from self._v2_timeline_instructions_to_tweets(obj)

  File "C:\Users\aafef\anaconda3\lib\site-packages\snscrape\modules\twitter.py", line 487, in _v2_timeline_instructions_to_tweets
    yield from self._v2_instruction_tweet_entry_to_tweet(entry['entryId'], entry['content'], obj)

  File "C:\Users\aafef\anaconda3\lib\site-packages\snscrape\modules\twitter.py", line 510, in _v2_instruction_tweet_entry_to_tweet
    yield self._tweet_to_tweet(tweet, obj)

  File "C:\Users\aafef\anaconda3\lib\site-packages\snscrape\modules\twitter.py", line 642, in _tweet_to_tweet
    return self._make_tweet(tweet, user, **kwargs)

  File "C:\Users\aafef\anaconda3\lib\site-packages\snscrape\modules\twitter.py", line 609, in _make_tweet
    i = kwargs['tcooutlinks'].index(card.url)

KeyError: 'tcooutlinks'

```

**Comment by TheTechRobo** [comment] 2022-11-28 00:19
Please provide the output of `snscrape --version`

**Comment by Afefa** [comment] 2022-11-30 05:38
snscrape 0.4.3.20220107.dev65+g46a6030

**Comment by JustAnotherArchivist** [comment] 2022-12-01 15:22
That can't be correct. The code in your traceback doesn't exist in this version. I think that this is a duplicate of #411.

**Comment by JustAnotherArchivist** [comment] 2022-12-01 15:29
And to answer your question about the CLI, the same query works fine there. In a sane shell, you'd do

    snscrape twitter-search '"" geocode:"..."'

You're on Windows though, where the quoting rules are different, so I don't know the correct syntax there.

**Comment by Afefa** [comment] 2022-12-04 06:24
> 

I tried the command and it did not give me any result!

`(dl_text) C:\Users\aafef>snscrape --jsonl --progress --max-results 100  --since 2020-6-1 twitter-search "'حضري'  geocode:'21.492500, 39.177570, 10k' until:2022-07-31"  > JLocation-query-tweets.json
Finished, 0 results`

While when I tried the same command without location, it did work:

`(dl_text) C:\Users\aafef>snscrape --jsonl --progress --max-results 1000  --since 2020-6-1 twitter-search "'حضري'  until:2022-07-31"  > JLocation-query-tweets.json
Scraping, 100 results so far
Scraping, 200 results so far
Scraping, 300 results so far
Scraping, 400 results so far
Scraping, 500 results so far
Scraping, 600 results so far
Scraping, 700 results so far
Scraping, 800 results so far
Scraping, 900 results so far
Scraping, 1000 results so far
Stopped scraping after 1000 results due to --max-results`

**Comment by Afefa** [comment] 2022-12-04 08:27
I was running my code now using this version: snscrape 0.4.3.20220107.dev66+ge09aea7

This error appears
```
File "C:\Users\aafef\OneDrive\Desktop\Afefa_PhD\Coding\Python Learning\snscrape\snscrapeByLocation.py", line 43, in <module>
    df_coord = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(

  File "C:\Users\aafef\anaconda3\envs\dl_text\lib\site-packages\pandas\core\frame.py", line 3461, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]

  File "C:\Users\aafef\anaconda3\envs\dl_text\lib\site-packages\pandas\core\indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)

  File "C:\Users\aafef\anaconda3\envs\dl_text\lib\site-packages\pandas\core\indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")

KeyError: "['content'] not in index" 
```

and this is the line of code that are responsible for the error
`#====== Riyadh ============
loc = '24.633333, 46.716667, 10km'
df_coord = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    '"" geocode:"{}"'.format(loc)).get_items(), 600))[['user', 'date', 'content']]
df_coord['user_location'] =  df_coord['user'].apply(lambda x: x['location'])`

**Comment by JustAnotherArchivist** [comment] 2022-12-04 15:33
You changed the quotes. Twitter requires double quotes in the search query. The outer quotes are for the shell. I don't know how you need to write this on Windows, I only use sane operating systems.

The second error is something in your code, not in snscrape.

**Comment by JustAnotherArchivist** [comment] 2022-12-04 18:45
Either way, I'm closing this as a duplicate of #411 since the original `KeyError` is not possible in current dev.

**Closed by JustAnotherArchivist** 2022-12-04 18:45 UTC
