### ISSUE TITLE
failing with code 215 bad authentication

### ISSUE THREAD

**Issue by anjalitambe** [JustAnotherArchivist/snscrape#648] opened 2023-01-11 19:15 UTC
Hi, 
My code worked fine a couple days back. I am working through getting around this problem. Could you please help?
`{"errors":[{"message":"Bad Authentication data","code":215}]}`

I have errors on the CLI

```
PS C:\Users\ProjectNameRetracted> snscrape --jsonl --progress --max-results 10 twitter-search "hello" --top
2023-01-11 14:09:16.682  ERROR  snscrape.base  Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=hello&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo: non-200 status code

2023-01-11 14:09:16.682  CRITICAL  snscrape.base  4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=hello&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo failed, giving up.
2023-01-11 14:09:16.756  CRITICAL  snscrape._cli  Dumped stack and locals to C:\Users\AppData\Local\Temp\snscrape_locals_u7h_743w
Traceback (most recent call last):
  File "C:\Users\anaconda3\envs\ProjectNameRetracted\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\anaconda3\envs\ProjectNameRetracted\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\anaconda3\envs\ProjectNameRetracted\Scripts\snscrape.exe\__main__.py", line 7, in <module>
  File "C:\Users\anaconda3\envs\ProjectNameRetracted\lib\site-packages\snscrape\_cli.py", line 318, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "C:\Users\anaconda3\envs\ProjectNameRetracted\er.py", line 1455, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', _TwitterAPIType.V2, params, paginationParams, cursor = self._cursor):
  File "C:\Users\anaconda3\envs\ProjectNameRetracted\er.py", line 721, in _iter_api_data
    obj = self._get_api_data(endpoint, apiType, reqParams)
  File "C:\Users\anaconda3\envs\ProjectNameRetracted\er.py", line 691, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
  File "C:\Users\anaconda3\envs\NameRedacted\lib\site-packages\snscrape\base.py", line 221, in _get
    return self._request('GET', *args, **kwargs)
  File "C:\Users\anaconda3\envs\NameRedacted\lib\site-packages\snscrape\base.py", line 217, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=hello&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo failed, giving up.
```

**Comment by Waterfall2023** [comment] 2023-01-11 19:18
hi there, I was just about to post the same question. Everything was running fine till yesterday and then received the same error
{"errors":[{"message":"Bad Authentication data","code":215}]}

**Comment by JustAnotherArchivist** [comment] 2023-01-11 19:20
I'm unable to reproduce that exact error, but it also fails for me for a different reason (#647). Please provide all the information requested in the bug issue template.

**Comment by AntoinePaix** [comment] 2023-01-11 21:24
SOLUTION: Twitter has started adding TLS fingerprinting. Additional ciphers must be passed to the `Session` object of requests to bypass the protection.

```python
import ssl

import requests
from requests.adapters import HTTPAdapter
from urllib3.poolmanager import PoolManager
from urllib3.util.ssl_ import create_urllib3_context

# see "openssl ciphers" command for cipher names
CIPHERS = "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384"


class TlsAdapter(HTTPAdapter):
    def __init__(self, ssl_options=0, **kwargs):
        self.ssl_options = ssl_options
        super(TlsAdapter, self).__init__(**kwargs)

    def init_poolmanager(self, *pool_args, **pool_kwargs):
        ctx = create_urllib3_context(ciphers=CIPHERS, cert_reqs=ssl.CERT_REQUIRED, options=self.ssl_options)
        self.poolmanager = PoolManager(*pool_args, ssl_context=ctx, **pool_kwargs)

adapter = TlsAdapter(ssl.OP_NO_TLSv1 | ssl.OP_NO_TLSv1_1)  # prioritize TLS 1.2
session = requests.Session()
session.mount("https://", adapter)
session.get('<twitter_api_url>')
```

**Comment by JustAnotherArchivist** [comment] 2023-01-11 21:26
@AntoinePaix Thank you! That was exactly my suspicion, but I didn't have time to investigate the ciphers yet. Will implement later.

**Comment by AntoinePaix** [comment] 2023-01-11 21:28
You're welcome. You can also use the `httpx` client which works well on twitter without patching SSL certificates and has the same API as requests.

**Comment by boolerrain** [comment] 2023-01-11 21:38
Hello. Would you be able to explain this fix to someone who doesn't understand, such as your grandmother. I do not really know how to implement this and fix snscrape. Any help is appreciated thank you.

**Comment by JustAnotherArchivist** [comment] 2023-01-11 21:39
@boolerrain Twitter's a party pooper and changed things on their servers so that snscrape can no longer access it. It will be fixed later tonight.

**Comment by 0bmay** [comment] 2023-01-11 21:48
@AntoinePaix updating my local copy of base.py adding in the cipher code in the proper sapce worked like a charm to get the tweets..

**Comment by AntoinePaix** [comment] 2023-01-11 21:53
@0bmay Nice!

**Comment by Goitsemedi888** [comment] 2023-01-11 22:38
@0bmay did you just add the code above or edit it in a specific field. Still a novice !

**Comment by Ramizworking** [comment] 2023-01-11 22:45
@JustAnotherArchivist @AntoinePaix GJ both guys ! You are awesome !

**Comment by 0bmay** [comment] 2023-01-11 22:49
@Goitsemedi888 i added the imports to the top of the file as well as the class. 

The lines of code that get the requests.Session() and around it into the function in base.py that called requests.Session()

I am not at the computer at the moment to give exact code lines or make a proper PR.

**Comment by JustAnotherArchivist** [comment] 2023-01-11 22:57
@Goitsemedi888 I recommend waiting for the proper fix then. Should be ready within the next couple hours.

**Comment by Goitsemedi888** [comment] 2023-01-11 22:59
I was curious as to how it's done. I had resolved to wait patiently. thank you for staying on top of this!

**Comment by Malai237** [comment] 2023-01-11 23:12
Thanks @AntoinePaix for saving the day.

**Comment by JustAnotherArchivist** [comment] 2023-01-12 00:42
I suspect that most comments here are actually about the 404 issue, i.e. #647, which is indeed fixed by the TLS cipher change. From now on, please only comment here if you have information about the 'Bad authentication data' error in the original report. (I still have no idea how to reproduce that.) Follow #647 to see when the fix suggested by @AntoinePaix lands.

**Comment by sw33tyin4** [comment] 2023-01-12 02:51
I also are facing the same issue of Bad Authentication code 215 problem yesterday. Not sure how to resolved. These are the errors displayed:

![Error_1](https://user-images.githubusercontent.com/97866325/211964353-c2fe872b-e11e-470b-b290-fcdedf097a6e.png)
![Error_2](https://user-images.githubusercontent.com/97866325/211964360-f625ab99-549c-4399-af7b-c08ad7c3d4a5.png)

**Comment by sw33tyin4** [comment] 2023-01-12 02:55
I am using jupyter notebook, may I know how to get the CLI yea? Thank you

**Comment by sw33tyin4** [comment] 2023-01-12 02:56
> @sw33tyin4 Are you certain you're hitting the 'Bad authentication data' error, not the 404 from #647? They look the same unless you have a dump file from the CLI.

When I clicked the error link it shows this:

![Error_3](https://user-images.githubusercontent.com/97866325/211965007-33988225-c9fe-4d51-8a25-15a70de75f25.png)

**Comment by JustAnotherArchivist** [comment] 2023-01-12 02:58
Ah, so that's where the confusion comes from... Yeah, you can just open that URL in a browser and expect it to return the same data as snscrape sees.

@anjalitambe @Waterfall2023 Is that how you originally came across that error message?

**Comment by sw33tyin4** [comment] 2023-01-12 02:59
> Ah, so that's where the confusion comes from... Yeah, you can't just open that URL in a browser and expect it to return the same data as snscrape sees.
> 
> @anjalitambe @Waterfall2023 Is that how you originally came across that error message?

May I know is there a solution to solve this yea? it just happened yesterday.

Thank you.

**Comment by JustAnotherArchivist** [comment] 2023-01-12 03:01
If my interpretation above is correct, this is a duplicate of #647. But your code would also run into #634 since you're not using the 'top' search order.

**Comment by sidward35** [comment] 2023-01-12 09:02
@Goitsemedi888 You can see the _temporary_ fix on my fork [here](https://github.com/sidward35/snscrape/commit/b0fab9c13d66d109defb55ddce8fe8f9e7cbc1da). Lines 11-16, 21-30, and 162-163 were added in `base.py`.

**Comment by NUELBUNDI** [comment] 2023-01-12 09:06
@JustAnotherArchivist Please advise if the problem as been resolved?

**Comment by nathan1505** [comment] 2023-01-12 10:45
@AntoinePaix I did find that class `Scraper` called `requests.Session()` but I have a hard time modifying the class. Would you please tell me how you add the `requests.Session()` lines below into the class? Appreciate your help.
``` python
adapter = TlsAdapter(ssl.OP_NO_TLSv1 | ssl.OP_NO_TLSv1_1)  # prioritize TLS 1.2
session = requests.Session()
session.mount("https://", adapter)
session.get('<twitter_api_url>')
```

**Comment by sidward35** [comment] 2023-01-12 11:06
Hey @nathan1505 @Goitsemedi888, I've been able to get it working and added those lines of code as shown in [this commit](https://github.com/sidward35/snscrape/commit/b0fab9c13d66d109defb55ddce8fe8f9e7cbc1da). 

You can also simply run:
``` bash
pip3 install git+https://github.com/sidward35/snscrape.git
```

Just a temporary fix for the time being, hope this helps.

**Comment by nobody613** [comment] 2023-01-12 12:42
Doesn't work for me 
I use the tool I wrote, but in the bottom line send Ialmost same requests like this  excellent tool

Some notes :
1. Yesterday when the problem started:
Twitter sent in response to:
api.twitter.com/2/search/adaptive.json

This error message:
"message":"Bad Authentication data""
Today it changed to:
 'message': 'Sorry, that page does not exist'

2. The problem started after this update:
https://twittercommunity.com/t/announcing-the-deprecation-of-v1-1-statuses-filter-endpoint/182960

3. The address:
api.twitter.com/graphql/
still responding

4. I thought the problem was with the token - but no - the same token responds to requests to "graphql"

5.  The SSL changes don't work for me (I use a different tool and allso tried to insert them into your tool - and it didn't work too)


Thanks to anyone who has comments and explanations that will help

**Comment by boolerrain** [comment] 2023-01-12 14:28
So has anyone got Snscrape to run?

**Comment by nobody613** [comment] 2023-01-12 14:30
> So has anyone got Snscrape to run?
no

**Comment by JustAnotherArchivist** [comment] 2023-01-12 16:02
Closing this as an incomplete duplicate of #647 since the original reporters have not come back and there is a reasonable explanation for how they got to that unrelated error message.

**Closed by JustAnotherArchivist** 2023-01-12 16:02 UTC
Labels: incomplete

**Comment by Neillife** [comment] 2023-01-12 17:45
External solution using classes in modules.twitter.

Change TwitterSearchScraper in the example below to the class you use.


```python
import snscrape.modules.twitter as SnTwitter
import ssl
from requests.adapters import HTTPAdapter
from urllib3.poolmanager import PoolManager
from urllib3.util.ssl_ import create_urllib3_context

# see "openssl ciphers" command for cipher names
CIPHERS = "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384"


class TlsAdapter(HTTPAdapter):
    def __init__(self, ssl_options=0, **kwargs):
        self.ssl_options = ssl_options
        super(TlsAdapter, self).__init__(**kwargs)

    def init_poolmanager(self, *pool_args, **pool_kwargs):
        ctx = create_urllib3_context(ciphers=CIPHERS, cert_reqs=ssl.CERT_REQUIRED, options=self.ssl_options)
        self.poolmanager = PoolManager(*pool_args, ssl_context=ctx, **pool_kwargs)

class TwitterMain():
    def __init__(self):
        self.TweetUrl = []

    def procsesTweet(self):
        self.TwitterUserQuery = f"(from:elonmusk) until:2023-01-13 since:2023-01-01"
        adapter = TlsAdapter(ssl.OP_NO_TLSv1 | ssl.OP_NO_TLSv1_1)
        
        tss = SnTwitter.TwitterSearchScraper(self.TwitterUserQuery)
        tss._session.mount("https://", adapter)
        
        tweets = list(tss.get_items())

        for i in range(len(tweets)):
            tweet :SnTwitter.Tweet = tweets[i]

            self.TweetUrl.append(tweet.url)

tw = TwitterMain()
tw.procsesTweet()
print(tw.TweetUrl)

```

**Comment by Waterfall2023** [comment] 2023-01-12 17:45
@JustAnotherArchivist Apologies, I missed your question earlier today. Indeed, I clicked on the url and saw this error message
{"errors":[{"message":"Bad Authentication data","code":215}]}
I still cannot run my query - is there a suggestion on how to resolve this? I am not sure I understood the solution on this matter. Please forgive my naivity, still new at coding

**Comment by JustAnotherArchivist** [comment] 2023-01-12 18:16
@Waterfall2023 Thanks for confirming. There's no official solution at the moment, but there will be later today when I finish testing. See my comments on the linked issue for details, and keep an eye on that one to see when that happens.

**Comment by Waterfall2023** [comment] 2023-01-12 18:23
@JustAnotherArchivist Thank you very much for that! Will keep an eye

**Comment by lucasrueda01** [comment] 2023-01-13 06:34
Having the same problem, code 215. May i know if this will be fixed and when?

**Comment by brow73** [comment] 2023-03-16 23:35
> @Waterfall2023 Thanks for confirming. There's no official solution at the moment, but there will be later today when I finish testing. See my comments on the linked issue for details, and keep an eye on that one to see when that happens.

have any solution? thx for help

**Comment by zz9tf** [comment] 2023-04-22 18:12
Hi, I have the same issue today. I detailly checked the code in this package. And I think it might because the method of getting auth doesn't work, like below:

In sessions.py, line 479:
![image](https://user-images.githubusercontent.com/77183284/233800006-5813ab14-bf44-4718-a26c-5efe760034ae.png)

The result is:
![image](https://user-images.githubusercontent.com/77183284/233800038-35c85fff-dbbd-42ee-98ed-9ef826a1ffed.png)


I'm not sure why this happened, but probably this's the point why twitter block the code.(still try to figure out the reason)
