### ISSUE TITLE
How use the proxy?

### ISSUE THREAD

**Issue by break404** [JustAnotherArchivist/snscrape#90] opened 2020-09-28 00:53 UTC
Hello,i want to use proxy for this project,i modify base.py,eg:
proxy={"http":"http://127.0.0.1:8001"}
```
 req = self._session.prepare_request(
                requests.Request(method, url, params=params, data=data, headers=headers, proxies=self.proxy))
```
but result this error code:
```
    requests.Request(method, url, params=params, data=data, headers=headers, proxies=self.proxy))
TypeError: __init__() got an unexpected keyword argument 'proxies'
```

**Comment by JustAnotherArchivist** [comment] 2020-09-28 01:19
Duplicate of #74

**Closed by JustAnotherArchivist** 2020-09-28 01:19 UTC
Labels: duplicate
