### ISSUE TITLE
"Unable to find guest token" after running many short Twitter scrapes

### ISSUE THREAD

**Issue by Logenleedev** [JustAnotherArchivist/snscrape#326] opened 2021-12-11 03:34 UTC
I saw this error when I run my code
```
---------------------------------------------------------------------------
ScraperException                          Traceback (most recent call last)
<ipython-input-18-000bfba11f8b> in <module>
      1 # Using TwitterSearchScraper to scrape data and append tweets to list
      2 for x in D_username:
----> 3     for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:{}'.format(x)).get_items()):
      4         if i>maxTweets:
      5             break

/opt/homebrew/lib/python3.9/site-packages/snscrape/modules/twitter.py in get_items(self)
    554                         del paginationParams['tweet_search_mode']
    555 
--> 556                 for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams, cursor = self._cursor):
    557                         yield from self._instructions_to_tweets(obj)
    558 

/opt/homebrew/lib/python3.9/site-packages/snscrape/modules/twitter.py in _iter_api_data(self, endpoint, params, paginationParams, cursor, direction)
    248                 while True:
    249                         logger.info(f'Retrieving scroll page {cursor}')
--> 250                         obj = self._get_api_data(endpoint, reqParams)
    251                         yield obj
    252 

/opt/homebrew/lib/python3.9/site-packages/snscrape/modules/twitter.py in _get_api_data(self, endpoint, params)
    217 
    218         def _get_api_data(self, endpoint, params):
--> 219                 self._ensure_guest_token()
    220                 r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
    221                 try:

/opt/homebrew/lib/python3.9/site-packages/snscrape/modules/twitter.py in _ensure_guest_token(self, url)
    198                         self._apiHeaders['x-guest-token'] = self._guestToken
    199                         return
--> 200                 raise snscrape.base.ScraperException('Unable to find guest token')
    201 
    202         def _unset_guest_token(self):

ScraperException: Unable to find guest token
```

I am pretty sure this does not come from my bug. Are there ways to fix it?

**Comment by JustAnotherArchivist** [comment] 2021-12-11 10:51
Is this happening randomly or permanently?

**Comment by Logenleedev** [comment] 2021-12-11 14:12
Well. I tried several times and it is always happening.

**Comment by Logenleedev** [comment] 2021-12-11 14:13
However, I remembered that when I used the API four weeks ago, it does not have this problem.

**Comment by sausageface** [comment] 2021-12-11 14:36
i just wanted to jump in here, this has been working fine for me over the last 6 months (scraping 600 accounts every 30minutes) but the last 24 hours i keep getting the same guest token error

**Comment by p0ur1a** [comment] 2021-12-11 14:47
I'm having the same issue. I used to run more than 20 threads scraping at the same time. But I've been receiving `snscrape.base.ScraperException: Unable to find guest token` since yesterday.

**Comment by TheTechRobo** [comment] 2021-12-11 14:59
Does going to the Twitter website show you anything like a rate limit?

**Comment by Logenleedev** [comment] 2021-12-11 15:04
I agree with @sausageface. @TheTechRobo nope. I think for each person I scrapped, I was barely close to the rate limit since i set it to 1000 per person.

**Comment by Logenleedev** [comment] 2021-12-11 15:05
I sincerely hope someone can fix it as rewriting the code and switching API is very horrible.

**Comment by Logenleedev** [comment] 2021-12-11 15:19
> Is this happening randomly or permanently?



> Is this happening randomly or permanently?

Also, the error comes from this line:

```
----> 3     for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:{}'.format(x)).get_items()):
```

**Comment by JustAnotherArchivist** [comment] 2021-12-11 17:18
Interesting. So the common factor seems to be a large number of independent scrapes. I have an idea for that, but...

When you get this error with snscrape, you can still use Twitter's search in a browser (from the same IP and without prior cookies) at the same time? I've never seen that behaviour before on Twitter.

**Comment by sausageface** [comment] 2021-12-11 17:39
Ive tried it whilst browsing both the twitter app and twitter.com and I still get the error when i run my script.
FWIW im attempting to scrape the last 30 minutes of posts from my user list of 600 users. At a rough count thats around 50 tweets total when i just ran it. 

At the same time i can scrape a whole archive from a single user > 1500 tweets without an issue so from the behaviour i'm experiencing its seems like the error comes when hoping from account to account.

hope that adds some colour to whats going on

**Comment by Logenleedev** [comment] 2021-12-11 19:47
> Interesting. So the common factor seems to be a large number of independent scrapes. I have an idea for that, but...
> 
> When you get this error with snscrape, you can still use Twitter's search in a browser (from the same IP and without prior cookies) at the same time? I've never seen that behaviour before on Twitter.

Hmmm. Do you have any ideas on how to fix this? I am not sure whether the API is banned by Twitter or just some bugs.

**Comment by JustAnotherArchivist** [comment] 2021-12-11 23:21
Yeah, the hopping is certainly the primary issue here. I just pushed a commit which should help alleviate this problem by reusing the token as long as possible. If you still get the error permanently, that probably means that Twitter banned your IP, but it sounds like these are only temporary blocks (so far). Please let me know how it goes.

**Comment by Logenleedev** [comment] 2021-12-12 00:56
> Thanks! I retried and I can tell it is better than last time since the scrapper last longer. However, eventually, the bug reappears. Not sure whether it works for other people.

**Comment by JustAnotherArchivist** [comment] 2021-12-12 04:19
Too bad, although good to hear that it's an improvement. Not sure what else can be done about this in terms of code changes. In my experience, Twitter bans are normally targeted at an IP.

I have two ideas you can try for your specific case though.
The first is to combine multiple users into a single search using `TwitterSearchScraper('from:user1 OR from:user2 OR ...')`. Potentially conducting many different searches in a short time window is what causes Twitter to temporarily ban you. Note that there's a limit on `OR` clauses and long queries (#211).
The second idea is to increase the number of retries. This will only work if these bans are very short-lived. Due to #325, snscrape now also attempts to get a token several times. As with other requests, there's an exponential backoff starting at 1 second and doubling on every attempt. The default is 3 retries, so 4 attempts in a total of 7 seconds. If you increase the number of retries to 5, that'll be 31 seconds. This change can be done by passing a `retries` kwarg to the scraper, e.g. `TwitterSearchScraper('query', retries = 5)`.

Also, as I didn't mention it previously: this code change has no effect when using the CLI. Using a big `OR` query (or rather just avoiding many small searches) is even more important there.

**Comment by Logenleedev** [comment] 2021-12-12 04:36
Interesting. I am using the library in Python (Jupyter Notebook). Do you think it is going to work if I switch another device or sth? Not sure whether people commented in this thread solve the problem. If not, then maybe twitter banned us all and we need to figure out sth else like the solution you proposed.

**Comment by JustAnotherArchivist** [comment] 2021-12-12 18:11
> Do you think it is going to work if I switch another device or sth?

snscrape in general still works fine, so if you use it from an unrelated IP address, that would likely 'fix' it. But I don't know what their ban heuristics are, so you might just get that address banned quickly again. Also, from the previous comments, I got the impression that these bans aren't permanent and it should just work again after a while...?

> can snscrape retrieve a list of tweet id by user id or username?

Twitter returns all that other information in the same response anyway. I'm not aware of a way to retrieve only tweet IDs.

**Comment by Logenleedev** [comment] 2021-12-13 00:49
Yeah. I used another computer and it reported the same error...

**Comment by EssbieWGT** [comment] 2021-12-13 15:02
I've been running into this same issue since Wednesday of last week. On a whim I tried this as a workaround, and it works ALMOST every time. 

```python
    for i in handles:
        print("Pulling " + i )
        data = "'from:"+i+" since:"+useDate+"'"
        try:
            tweets = snscrape.modules.twitter.TwitterSearchScraper(data)
            for j in tweets.get_items():
                tOut.append(j)
        except:
            print(i)
            try:
                print(i)
                tweets = snscrape.modules.twitter.TwitterSearchScraper(data)
                for j in tweets.get_items():
                    tOut.append(j)
            except:
                print("Passed")
```

Obviously, not an ideal solution, but it does work about 19 out of 20 times. 

Also, I've been tracking when the error shows up, and it does, so far, appear to be random. I initially thought it was being thrown only with accounts with pinned Tweets, but after I tracked it for a couple runs, there was no longer any obvious pattern. 

In my limited observations (12 runs that I've tracked so far) I've seen the error come up as soon as the third handle, and as late as the 47th. Once it happens the first time, it has run between 8 and 27 handles before throwing the error again. I randomized my list of handles to try to make sure the same one's don't get caught over and over, but it does not appear theres that specific handles are more susceptible than others, or that list position matters anyways. 

For reference, I do a daily run of congressional twitter accounts for personal use. Is the same list of just under 500 handles run each day, which usually nets out to around 2,400 Tweets.

**Comment by Logenleedev** [comment] 2021-12-13 23:35
Just a follow up question on the thread. Do people fix the bug? It stills happen in my end...

**Comment by albi89** [comment] 2021-12-14 03:18
SnScrape worked for me once around December 7/8, 2021. In one day I scraped over a million tweets using code below in Jupyter Lab. This was for a school project trying to get sentiment of 3 cryptos for each day in 2021 to see if it changed throughout the year. Essentially I wanted 1000 random tweets for every day in 2021 on each of these 3 cryptos.  

Since then, it has not worked and my developer account was also banned. Not sure why. I have since gotten two other developer accounts and have tried to access the API from different IPs/Locations, but my loop will never go past the first 12 days of January 2021. It doesn't matter if I want 3000 tweets per day or 30 tweets per day. Once it reaches the first 10-12 days of January, the code breaks and gives me this error: 

**ScraperException: Unable to find guest token**

Below is mycode:

`# Using TwitterSearchScraper to scrape data and append tweets to list
tweet_list = []
tweet_count = 1000
start_date = '2021-01-01'
end_date = '2021-12-10'
cryptos = ['bitcoin','ethereum','dogecoin']

for d in range(len(dates_list)-1):
    for c in cryptos: 
        for i,tweet in enumerate(sns.TwitterSearchScraper(f'{c} lang:en since:{dates_list[d]} until:{dates_list[d+1]}').get_items()):
            if i>tweet_count:
                print(f'{c} {dates_list[d]}')
                break
            tweet_list.append([tweet.date, tweet.id, tweet.user.username, c, tweet.content])
               
# Creating a dataframe from the tweets list above
tweets_df = pd.DataFrame(tweet_list, columns=['Datetime', 'Tweet Id', 'Username', 'crypto', 'Text'])`

**Comment by JustAnotherArchivist** [comment] 2021-12-14 03:30
@EssbieWGT Good info, thank you.

@albi89 snscrape does not use the official API nor any account. I'm not sure how that getting banned is related to the problem at hand. Also note that your code will always get the 1000 last (i.e. closest to the end of the day) tweets on a particular day, not really a random sample.

@EssbieWGT @albi89 Have you tried using the latest dev version, and does it change anything for you?

**Comment by EssbieWGT** [comment] 2021-12-14 04:11
Just ran my script with the dev version, and it worked with no issues at all. Awesome! Thank you, sir!

**Comment by teemumantynen** [comment] 2021-12-14 11:24
The current development version works very well. During the previous few days about 10-20 % of queries failed because of error "Unable to find guest token". Now only one in about 1500 queries failed. Thank you very much.

**Comment by Logenleedev** [comment] 2021-12-14 15:29
> SnScrape worked for me once around December 7/8, 2021. In one day I scraped over a million tweets using code below in Jupyter Lab. This was for a school project trying to get sentiment of 3 cryptos for each day in 2021 to see if it changed throughout the year. Essentially I wanted 1000 random tweets for every day in 2021 on each of these 3 cryptos.
> 
> Since then, it has not worked and my developer account was also banned. Not sure why. I have since gotten two other developer accounts and have tried to access the API from different IPs/Locations, but my loop will never go past the first 12 days of January 2021. It doesn't matter if I want 3000 tweets per day or 30 tweets per day. Once it reaches the first 10-12 days of January, the code breaks and gives me this error:
> 
> **ScraperException: Unable to find guest token**
> 
> Below is mycode:
> 
> ```python
> import snscrape.modules.twitter as sns
> 
> tweet_list = []
> tweet_count = 1000
> start_date = '2021-01-01'
> end_date = '2021-12-10'
> cryptos = ['bitcoin','ethereum','dogecoin']
> 
> for d in range(len(dates_list)-1):
>     for c in cryptos: 
>         for i,tweet in enumerate(sns.TwitterSearchScraper(f'{c} lang:en since:{dates_list[d]} until:{dates_list[d+1]}').get_items()):
>             if i>tweet_count:
>                 print(f'{c} {dates_list[d]}')
>                 break
>             tweet_list.append([tweet.date, tweet.id, tweet.user.username, c, tweet.content])
>                
> tweets_df = pd.DataFrame(tweet_list, columns=['Datetime', 'Tweet Id', 'Username', 'crypto', 'Text'])
> ```

I am sure the error is not related to banned API request. The whole point of snscrape is to not use twitter official API request channel and authorization. So there is no way twitter can know what you are doing.

**Comment by pinakin9526** [comment] 2021-12-14 19:02
I got the same issue when I was using previous year dates. And @JustAnotherArchivist are you using V1.1 API for twitter? I have not gone through the all sources yet. @Logenleedev I guess it is using Official API to retrieve some information, i can see some endpoints in source. But I am not sure if that's causing an issue.

**Comment by JustAnotherArchivist** [comment] 2021-12-14 19:04
No. As mentioned above:

> snscrape does not use the official API nor any account.

It uses the undocumented, unauthenticated, private API that is used by the website.

**Comment by albi89** [comment] 2021-12-15 00:58
@JustAnotherArchivist @EssbieWGT @Logenleedev       I realize snscrape does not use the Twitter API; I was just trying to add some color to this issue by mentioning this detail, since it seems like we can't properly identify what's causing the issue. Thought it might be useful information on this bug that it is somehow related to the user's IP address. Idk...

I was able to get snscraper working again though. I queried 600K tweets overnight for what I mentioned above. Here's what I did: 
1. Changed IP address
2. Reinstalled snscraper developer
3. Queried at around 2am 

Of these, I'm sure the thing that made a difference was reinstalling snscraper developer. Maybe that in combination with IP change. Just my 2 cents, you guys probably know more. Hope this helps someone else.

**Comment by JustAnotherArchivist** [comment] 2021-12-15 01:15
My guess is that Twitter recently decided to ban IPs that request new guest tokens at a high rate. Prior to the commit above, every scrape with snscrape fetched a new token. That's fine if the scrapes are running for a while, but for short scrapes like the ones mentioned in this issue, it might mean requesting a new token every couple seconds. It's pretty plausible that Twitter might not like that. With the commit, snscrape by default reuses the token until it expires (though that only works when using snscrape from Python, not with the CLI).

An IP change may still be required to get around the ban from previous attempts, but that's more of a symptom than the actual bug here. I think the bug is fixed by the commit above, which is also in the latest release 0.4.1 from a couple hours ago.

**Comment by p0ur1a** [comment] 2021-12-15 12:44
@JustAnotherArchivist  I installed the latest dev version (0.4.1.20211214) and scraped with 12 threads. Prior to the update that you mentioned, some threads would fail with `Unable to find guest token` error and the others would do just fine. after the update nothing changed but the error message! now I'm getting `AttributeError: 'TwitterSearchScraper' object has no attribute '_set_random_user_aget'` error for some of my scraping threads. So after 382 minutes of scraping with 12 threads, 3 of them got the error and failed. I hope my comment was helpful for fixing the problem.

**Comment by TheTechRobo** [comment] 2021-12-15 14:41
JAA put a typo in a recent commit https://github.com/JustAnotherArchivist/snscrape/commit/7fdc8bcb53047825ed256a428f8ef6b12611dcea.

![image](https://user-images.githubusercontent.com/52163910/146206797-4933aea5-b529-4d0e-ad9f-ca20b5dbc0a7.png)

**Comment by Logenleedev** [comment] 2021-12-15 15:05
Just want to add some info to @JustAnotherArchivist. I uninstall the dev package and reinstall it. So far, my code is still running and there is no error, which is good but also weird lol.

**Comment by JustAnotherArchivist** [comment] 2021-12-15 16:37
@p0ur1a Oops, sorry about that, fixed in dev, will release a new version later.

**Closed** 2021-12-15 18:27 UTC
Labels: bug, module:twitter

**Comment by MattiaG98** [comment] 2022-01-03 16:39
Hi, has anyone solved this problem?

**Comment by TheTechRobo** [comment] 2022-01-03 16:46
The latest version should delay the problem. However, this problem is caused by ratelimiting/IP banning. It's likely not something snscrape can fix.

**Comment by MattiaG98** [comment] 2022-01-03 16:48
Ok, thanks a lot @TheTechRobo

**Comment by TheTechRobo** [comment] 2022-01-03 16:48
BTW: If you're using the CLI rather than tyhe python API, then the problem isn't even delayed (yet) if I'm correct.

**Comment by JustAnotherArchivist** [comment] 2022-01-03 22:38
That's correct. Every CLI run is independent, so it can't reuse tokens, and you get temporarily banned more easily. Perhaps I'll add something to store the token on disk, but it's not as straightforward as you might think. I've filed a separate issue for that: #339

**Comment by EssbieWGT** [comment] 2022-01-06 02:08
Circling back on this...

I started running into this error on the API today. Worked fine on Monday, but now my script is failing right away. Just wanted to give you a heads up. 

```
Error retrieving https://twitter.com/search?f=live&lang=en&q=%27from%3Asenatorcantwell+since%3A2022-01-04%27&src=spelling_expansion_revert_c
lick: unable to find guest token
4 requests to https://twitter.com/search?f=live&lang=en&q=%27from%3Asenatorcantwell+since%3A2022-01-04%27&src=spelling_expansion_revert_clic
k failed, giving up.`
```

**Comment by TheTechRobo** [comment] 2022-01-06 03:02
Are you using it on some kind of server? AWS is known for being banned by Twitter.

**Comment by JustAnotherArchivist** [comment] 2022-01-06 03:49
Twitter slowly changed the way they're handing out guest tokens over the past month or so. The latest version of snscrape handles that. But that's #325, not this issue, which was caused by fast token churn.

**Comment by EssbieWGT** [comment] 2022-01-06 14:28
I'm running my script locally on my home network. I'll try updating my version of the package and see if that helps.
