### ISSUE TITLE
--format isn't getting all tweets from users profiles

### ISSUE THREAD

**Issue by sunyoid** [JustAnotherArchivist/snscrape#156] opened 2020-11-11 16:22 UTC
Whenever I run this code in cmd `snscrape --format '{content}'  twitter-user GhostGuy_918 > text_files_test_10.csv` it doesnt give me the whole list of tweets my friend tweeted.But when I run this code `snscrape --format '{content}' --max-results 1000 twitter-user textfiles > text_files_test_10.csv` it gives me all the results up to 1000. It also gives me a [traceback ](https://imgur.com/a/IjzBmIX)(its pretty long so I end up taking a picture).Can someone tell me whats the issue is? I don't understand why its doing this to only some user
Extra details: 
Version of snscrape: **snscrape 0.3.5.dev91+gfdc33d0**
Python version: 3.8
Operating system- Windows 10

**Comment by JustAnotherArchivist** [comment] 2020-11-11 18:09
> character maps to <undefined>

That's an issue with your terminal.

Duplicate of #122

**Closed by JustAnotherArchivist** 2020-11-11 18:09 UTC
