### ISSUE TITLE
ScraperException: 4 requests to

### ISSUE THREAD

**Issue by distbit0** [JustAnotherArchivist/snscrape#658] opened 2023-01-12 11:02 UTC
### Describe the bug

When I use the following query: 
conversation_id:1549827710406389760  -filter:unsafe (filter:safe OR -filter:safe)
or the query:
conversation_id:1549827710406389760  (filter:safe OR -filter:safe)

I receive the attached error.
Am connecting from a home internet connection.

### How to reproduce

    scraper = sntwitter.TwitterSearchScraper(
        "conversation_id:1549827710406389760  -filter:unsafe (filter:safe OR -filter:safe)"
    )
    sntwitter.TwitterTweetScraper(
        tweet_id, mode=sntwitter.TwitterTweetScraperMode.RECURSE
    ).get_items()

### Expected behavior

To not receive the attached error message

### OS / Distro

Ubuntu 22.04

### Output from `snscrape --version`

snscrape 0.4.3.20220106

### Scraper

twitter-search

### Backtrace
```
Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=conversation_id%3A1549827710406389760+-filter%3Aunsafe+%28filter%3Asafe+OR+-filter%3Asafe%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: non-200 status code
4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=conversation_id%3A1549827710406389760+-filter%3Aunsafe+%28filter%3Asafe+OR+-filter%3Asafe%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.
Traceback (most recent call last):
  File "/home/pimania/Dev/twitterConvo/main.py", line 178, in <module>
    replies = get_replies(tweet_id)
  File "/home/pimania/Dev/twitterConvo/main.py", line 75, in get_replies
    tweets = [tweet for tweet in scraper.get_items()]
  File "/home/pimania/Dev/twitterConvo/main.py", line 75, in <listcomp>
    tweets = [tweet for tweet in scraper.get_items()]
  File "/home/pimania/.local/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 680, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams, cursor = self._cursor):
  File "/home/pimania/.local/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 369, in _iter_api_data
    obj = self._get_api_data(endpoint, reqParams)
  File "/home/pimania/.local/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 339, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
  File "/home/pimania/.local/lib/python3.10/site-packages/snscrape/base.py", line 216, in _get
    return self._request('GET', *args, **kwargs)
  File "/home/pimania/.local/lib/python3.10/site-packages/snscrape/base.py", line 212, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=conversation_id%3A1549827710406389760+-filter%3Aunsafe+%28filter%3Asafe+OR+-filter%3Asafe%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.
```

### How are you using snscrape?

Module

**Comment by kareemrasheed89** [comment] 2023-01-12 15:34
Am facing same issue

**Comment by JustAnotherArchivist** [comment] 2023-01-12 15:58
Still a duplicate of #634

**Closed by JustAnotherArchivist** 2023-01-12 15:58 UTC
Labels: duplicate
