### ISSUE TITLE
Is possible to apply --until filter in twitter-profile CLI command?

### ISSUE THREAD

**Issue by PabloConcheiro** [JustAnotherArchivist/snscrape#597] opened 2022-11-24 17:15 UTC
snscrape --jsonl --until 2022-11-11 --since 2022-07-21 twitter-profile CTCM_bot.
Is there same way to filter data get in a twitter profile and not getting it until current date-time like the command above. Thank you in advance guys!

**Comment by JustAnotherArchivist** [comment] 2022-11-24 17:51
Duplicate of #81

**Closed by JustAnotherArchivist** 2022-11-24 17:51 UTC
