### ISSUE TITLE
error: ScraperException at /twitterscrape/

### ISSUE THREAD

**Issue by basilhaffar** [JustAnotherArchivist/snscrape#464] opened 2022-04-27 02:00 UTC
The application works fine locally in the virtual environment but when I deploy it on 'pythonanywhere' it gives an error...

ScraperException at /twitterscrape/
4 requests to https://twitter.com/search?f=live&lang=en&q=%28from%3AHibrpress%29+lang%3Aar+until%3A2022-04-28+since%3A2022-04-26+-filter%3Areplies&src=spelling_expansion_revert_click failed, giving up.

Exception Location: local/lib/python3.9/site-packages/snscrape/base.py, line 212, in _request

error start in this line:
gettweetitems = sntw.TwitterSearchScraper(quy).get_items()
    for tweet in gettweetitems: 

<img width="1383" alt="wedwwedwed" src="https://user-images.githubusercontent.com/38813131/165421863-398b0b07-3590-49b8-a465-aa5850af32db.png">

twitterscrape : is name of page.html

**Comment by JustAnotherArchivist** [comment] 2022-04-27 02:02
Where is 'the site'? AWS/Heroku, perhaps?

**Comment by basilhaffar** [comment] 2022-04-27 02:04
> Where is 'the site'? AWS/Heroku, perhaps?

pythonanywhere

**Comment by JustAnotherArchivist** [comment] 2022-04-27 02:05
Duplicate of #79 and #217

**Closed by JustAnotherArchivist** 2022-04-27 02:05 UTC
