### ISSUE TITLE
--jsonl report unrecognized arguments

### ISSUE THREAD

**Issue by SSSIBIR** [JustAnotherArchivist/snscrape#101] opened 2020-10-03 04:27 UTC
it seems like when i use `!snscrape --jsonl twitter-search "from:barackobama since:2015-09-10 until:2015-09-12" > baracktweets.txt` in jupyter notebook ,it reporte an error: snscrape: error: unrecognized arguments: --jsonl. where am i doing wrong? thanks.

**Comment by slbauman** [comment] 2020-10-03 07:23
You need to install the development version instead of the regular version from pip3.

> pip3 install git+https://github.com/JustAnotherArchivist/snscrape.git

**Comment by edsu** [comment] 2020-10-03 08:10
Seeing these over and over makes me think maybe now would be a good time for a new pypi release?

**Comment by JustAnotherArchivist** [comment] 2020-10-03 15:18
Duplicate of #77

@edsu There are a few things I still want to implement and fix before the next release. People just need to learn to search for issues before opening a new one.

**Closed by JustAnotherArchivist** 2020-10-03 15:18 UTC

**Comment by edsu** [comment] 2020-10-03 15:22
I tbink a lot of people rely on the GitHub README for documentation. In the future it would probably be good to develop on a branch. But I guess you probably didn't anticipate the heightened attention after twint stopped working!

**Comment by JustAnotherArchivist** [comment] 2020-10-03 16:23
Indeed I didn't, and thanks for the explanation where all these people came from. :-)

I consider the `master` branch the development version. Releases are using tags, and naturally the README will be accurate for those: https://github.com/JustAnotherArchivist/snscrape/blob/v0.3.4/README.md
But yeah, the situation is not ideal. I've been wanting to write a proper documentation for a long time but never got around to it. I suppose a description on PyPI would also help.

**Comment by SSSIBIR** [comment] 2020-10-03 16:34
> You need to install the development version from pip3 and it will work.
> 
> > pip3 install git+https://github.com/JustAnotherArchivist/snscrape.git



> 您需要从pip3安装开发版本，然后才能运行。
> 
> > pip3安装git + https://github.com/JustAnotherArchivist/snscrape.git

thanks

**Comment by SSSIBIR** [comment] 2020-10-03 16:53
> Indeed I didn't, and thanks for the explanation where all these people came from. :-)
> 
> I consider the `master` branch the development version. Releases are using tags, and naturally the README will be accurate for those: https://github.com/JustAnotherArchivist/snscrape/blob/v0.3.4/README.md
> But yeah, the situation is not ideal. I've been wanting to write a proper documentation for a long time but never got around to it. I suppose a description on PyPI would also help.

sorry for bothering, i did miss the closing issues, i`ll  look them first next time.
