### ISSUE TITLE
How to scrape limited number of tweets in a time frame?

### ISSUE THREAD

**Issue by ehsong** [JustAnotherArchivist/snscrape#341] opened 2022-01-04 11:57 UTC
I realized if I do maxTweets = 5000, it will scrape 5000 but not across the entire timeframe. Since I don't know how many tweets there are between a time frame, how can I scrape tweets between a time frame? For instance, if I scrape tweets from Jan 1 to Jan 4, I would like to see tweets on all the dates - Jan 1 - Jan 4.

```
output = []
for i,tweet in enumerate(sntwitter.TwitterSearchScraper(keyword + 'since:' +  start + ' until:' + \
                                                        stop + ' -filter:links -filter:replies').get_items()):
    if i > maxTweets :
        break
    output.append([tweet.id, tweet.date, tweet.content, tweet.outlinks, tweet.retweetCount, tweet.likeCount])
```

**Comment by JustAnotherArchivist** [comment] 2022-01-04 15:11
Duplicate of #152 and issues linked therein

**Closed by JustAnotherArchivist** 2022-01-04 15:11 UTC
