### ISSUE TITLE
Feature request: Twitter retweeters of a particular tweet

### ISSUE THREAD

**Issue by Arf9999** [JustAnotherArchivist/snscrape#153] opened 2020-11-05 12:38 UTC
The twitter web search doesn't surface retweets. Is it possible to scrape the retweeters of a particular twitter status?
i.e. scrape this page:
![image](https://user-images.githubusercontent.com/36820513/98242045-80a69400-1f74-11eb-8a88-6e5ee3dd907e.png)

**Comment by JustAnotherArchivist** [comment] 2020-11-05 14:00
Duplicate of #103

**Closed by JustAnotherArchivist** 2020-11-05 14:00 UTC
Labels: duplicate
