### ISSUE TITLE
Twitter scrapes sometimes fail on `PeriscopeBroadcastCard` with `TypeError: __init__() missing 1 required positional argument: 'thumbnailUrl'`

### ISSUE THREAD

**Issue by SomKen** [JustAnotherArchivist/snscrape#507] opened 2022-07-06 07:05 UTC
It appears that https://github.com/JustAnotherArchivist/snscrape/issues/407 has come up again? Thoughts? 

```
Traceback (most recent call last):
  File "scrapper.py", line 183, in <module>
    sptwitter.main()
  File "scrapper.py", line 58, in main
    self.channel.start_consuming()
  File "/usr/local/lib/python3.8/dist-packages/pika/adapters/blocking_connection.py", line 1880, in start_consuming
    self._process_data_events(time_limit=None)
  File "/usr/local/lib/python3.8/dist-packages/pika/adapters/blocking_connection.py", line 2041, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/usr/local/lib/python3.8/dist-packages/pika/adapters/blocking_connection.py", line 848, in process_data_events
    self._dispatch_channel_events()
  File "/usr/local/lib/python3.8/dist-packages/pika/adapters/blocking_connection.py", line 567, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/local/lib/python3.8/dist-packages/pika/adapters/blocking_connection.py", line 1507, in _dispatch_events
    consumer_info.on_message_callback(self, evt.method,
  File "scrapper.py", line 73, in callback
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(t_search).get_items()):
  File "/usr/local/lib/python3.8/dist-packages/snscrape-0.4.3.20220107.dev56+gd72b519-py3.8.egg/snscrape/modules/twitter.py", line 1450, in get_items
    yield from self._v2_timeline_instructions_to_tweets(obj)
  File "/usr/local/lib/python3.8/dist-packages/snscrape-0.4.3.20220107.dev56+gd72b519-py3.8.egg/snscrape/modules/twitter.py", line 804, in _v2_timeline_instructions_to_tweets
    yield from self._v2_instruction_tweet_entry_to_tweet(entry['entryId'], entry['content'], obj)
  File "/usr/local/lib/python3.8/dist-packages/snscrape-0.4.3.20220107.dev56+gd72b519-py3.8.egg/snscrape/modules/twitter.py", line 827, in _v2_instruction_tweet_entry_to_tweet
    yield self._tweet_to_tweet(tweet, obj)
  File "/usr/local/lib/python3.8/dist-packages/snscrape-0.4.3.20220107.dev56+gd72b519-py3.8.egg/snscrape/modules/twitter.py", line 1269, in _tweet_to_tweet
    kwargs['card'] = self._make_card(tweet['card'], _TwitterAPIType.V2, self._get_tweet_id(tweet))
  File "/usr/local/lib/python3.8/dist-packages/snscrape-0.4.3.20220107.dev56+gd72b519-py3.8.egg/snscrape/modules/twitter.py", line 1085, in _make_card
    return PeriscopeBroadcastCard(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'thumbnailUrl'
```

```
Package            Version
------------------ -----------------------------
ansible            5.8.0
ansible-core       2.12.6
awscli             1.24.10
beautifulsoup4     4.11.1
botocore           1.26.10
certifi            2019.11.28
chardet            3.0.4
charset-normalizer 2.1.0
colorama           0.4.4
cryptography       2.8
dbus-python        1.2.16
distro             1.4.0
docutils           0.16
elastic-transport  8.1.2
elasticsearch      7.17.1
filelock           3.7.1
idna               2.8
iotop              0.6
Jinja2             3.1.2
jmespath           1.0.0
lxml               4.9.1
MarkupSafe         2.1.1
packaging          21.3
pika               1.3.0
pip                20.0.2
prettytable        0.7.2
pyasn1             0.4.8
PyGObject          3.36.0
PyJWT              1.7.1
pyparsing          3.0.9
PySocks            1.7.1
python-dateutil    2.8.2
pytz               2022.1
PyYAML             5.4.1
requests           2.28.1
resolvelib         0.5.4
rsa                4.7.2
s3transfer         0.5.2
setuptools         45.2.0
six                1.14.0
snscrape           0.4.3.20220107.dev56+gd72b519
soupsieve          2.3.2.post1
ssh-import-id      5.10
urllib3            1.26.9
wheel              0.34.2
```

**Comment by SomKen** [comment] 2022-07-06 07:09
Just updated my pip packages for everything else and still have the same error.

```
Package            Version
------------------ -----------------------------
ansible            6.0.0
ansible-core       2.13.1
awscli             1.25.22
beautifulsoup4     4.11.1
botocore           1.27.23
certifi            2022.6.15
cffi               1.15.1
chardet            5.0.0
charset-normalizer 2.1.0
colorama           0.4.5
cryptography       37.0.4
dbus-python        1.2.16
distro             1.7.0
docutils           0.19
elastic-transport  8.1.2
elasticsearch      7.17.1
filelock           3.7.1
idna               3.3
iotop              0.6
Jinja2             3.1.2
jmespath           1.0.1
lxml               4.9.1
MarkupSafe         2.1.1
packaging          21.3
pika               1.3.0
pip                20.0.2
prettytable        3.3.0
pyasn1             0.4.8
pycparser          2.21
PyGObject          3.36.0
PyJWT              2.4.0
pyparsing          3.0.9
PySocks            1.7.1
python-dateutil    2.8.2
pytz               2022.1
PyYAML             6.0
requests           2.28.1
resolvelib         0.8.1
rsa                4.8
s3transfer         0.6.0
setuptools         63.1.0
six                1.16.0
snscrape           0.4.3.20220107.dev56+gd72b519
soupsieve          2.3.2.post1
ssh-import-id      5.11
urllib3            1.26.9
wcwidth            0.2.5
wheel              0.37.1
```

**Comment by JustAnotherArchivist** [comment] 2022-07-06 11:40
Search query?

**Comment by SomKen** [comment] 2022-07-07 16:10
I figured it out. I was able to setup a pipenv, install 3.8, then requirements, and everything then ran. Ubuntu 20.04.


Example query `{"from": "CNN", "since": "2010-09-28", "until": "2010-10-05"}`

**Comment by JustAnotherArchivist** [comment] 2022-07-10 22:01
I managed to reproduce this with tweet 1544746686316441600.

**Comment by ArtemBernatskyy** [comment] 2022-08-16 19:32
@SomKen @JustAnotherArchivist probably the same issue, installed from github, have you managed to find a fix for this issues? Thx!

```
Traceback (most recent call last):
  File "/root/someproject/twitter_analysis/parser.py", line 123, in <module>
    twitter_parser.parse()
  File "/root/someproject/twitter_analysis/parser.py", line 68, in parse
    for i, tweet in enumerate(
  File "/root/someproject/twitter_analysis/env/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 1454, in get_items
    yield from self._v2_timeline_instructions_to_tweets(obj)
  File "/root/someproject/twitter_analysis/env/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 804, in _v2_timeline_instructions_to_tweets
    yield from self._v2_instruction_tweet_entry_to_tweet(entry['entryId'], entry['content'], obj)
  File "/root/someproject/twitter_analysis/env/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 827, in _v2_instruction_tweet_entry_to_tweet
    yield self._tweet_to_tweet(tweet, obj)
  File "/root/someproject/twitter_analysis/env/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 1273, in _tweet_to_tweet
    kwargs['card'] = self._make_card(tweet['card'], _TwitterAPIType.V2, self._get_tweet_id(tweet))
  File "/root/someproject/twitter_analysis/env/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 1095, in _make_card
    return NewsletterCard(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'imageUrl'
```

**Comment by JustAnotherArchivist** [comment] 2022-08-16 19:35
@ArtemBernatskyy That's a similar but different bug. Please file a separate issue with all details as mentioned in the pinned issue.

**Closed** 2022-08-21 01:59 UTC
Labels: bug, module:twitter

**Comment by ArtemBernatskyy** [comment] 2022-08-21 09:53
FYI I wasn't been able to reproduce [my error](https://github.com/JustAnotherArchivist/snscrape/issues/507#issuecomment-1217074391) even with the same exact tweet (and same exact software), strange ...

**Comment by JustAnotherArchivist** [comment] 2022-08-21 16:15
@ArtemBernatskyy That's not surprising, Twitter's cards are a bit weird. I suspect that it's related to caching and slow refetching things like icons and thumbnails from third-party providers. So they omit it from the response very rarely, but it starts working again minutes to hours later. It doesn't help that the search only lets you filter for cards in tweets from the past week, so it's hard to actually test this on larger scales. Also, regression testing would be very difficult because you'd need to request a different rarely accessed tweet on every test run...
So yeah, errors like this might happen from time to time. With a complete issue including the dump file, I can probably fix most of them even if I can't reproduce them myself. So please file one if you ever manage to hit it again. :-)
