### ISSUE TITLE
(time sensitive) Scraping for top 5 posts

### ISSUE THREAD

**Issue by shreyaa2798** [JustAnotherArchivist/snscrape#612] opened 2022-12-03 05:56 UTC
Hi, I'm trying to scrape Twitter using snscrape. But the data that I get is just for latest posts but not for the top posts. Any idea on how to extract it. It is kind of an emergency, it would be really nice you could respond at your earliest convenience @edsu @ivan @peterk @jodizzle @JackDallas

**Comment by MAYUKH97** [comment] 2022-12-03 06:06
Hi @shreyaa2798 I also wanted to ask the same questions.. @edsu @ivan @peterk @jodizzle anyone of you can you please help.. us both.

Thanks in advance

**Comment by JustAnotherArchivist** [comment] 2022-12-03 06:11
Duplicate of #381

Please don't ping random people here (and search the issues first).

**Closed by JustAnotherArchivist** 2022-12-03 06:11 UTC

**Comment by shreyaa2798** [comment] 2022-12-03 06:41
How to extract data on verification mark for twitter handles? @JustAnotherArchivist 
Your help is much appreciated. Thanks in advance.
