### ISSUE TITLE
Tweets that are liked by a user

### ISSUE THREAD

**Issue by krsnad** [JustAnotherArchivist/snscrape#422] opened 2022-03-08 08:20 UTC
I don't see the **likes** api being used anywhere. Is it possible to get a user likes with current snscrape?
By *l*ikes** api, I mean this,

https://twitter.com/i/api/graphql/9MSTt44HoGjVFSg_u3rHDw/Likes

**Comment by TheTechRobo** [comment] 2022-03-08 13:57
Duplicate of #238. Is that API endpoint open to unregistered users? snscrape cannot and will not support authentication (#270)

**Comment by JustAnotherArchivist** [comment] 2022-03-08 19:32
Yes, several, see the issue @TheTechRobo linked.

**Closed** 2022-03-08 19:33 UTC
Labels: duplicate
