### ISSUE TITLE
twitter-user does not return all tweets

### ISSUE THREAD

**Issue by ejoebstl** [JustAnotherArchivist/snscrape#581] opened 2022-11-03 15:12 UTC
Hello, 

We recently stumbled over the following issue: 

```
snscrape --jsonl twitter-user chmlaw | wc -l
```

Returns 8 tweets. 

[Ther user has 12 tweets](https://twitter.com/chmlaw). I can't see a pattern why certain tweets are returned and others are not.

**Comment by JustAnotherArchivist** [comment] 2022-11-03 15:19
Duplicate of #468 and others. Twitter's search is weird and not entirely reliable. See also https://twitter.com/search?q=from:chmlaw&f=live displaying no results randomly.

**Closed** 2022-11-03 15:19 UTC
Labels: duplicate

**Comment by ejoebstl** [comment] 2022-11-04 11:16
Gotcha, thank you for pointing this out!
