### ISSUE TITLE
--jsonl option not working on pip3 install snscrape. It does work in the developement vesion

### ISSUE THREAD

**Issue by Eyon42** [JustAnotherArchivist/snscrape#180] opened 2021-01-07 19:58 UTC
```
$ snscrape --jsonl twitter-user user > tweets
usage: snscrape [-h] [--version] [-v] [--dump-locals] [--retry N] [-n N]
                [-f FORMAT] [--since DATETIME]
                {googleplus-user,telegram-channel,vkontakte-user,instagram-user,instagram-hashtag,instagram-location,gab-user,gab-user-comments,gab-user-media,facebook-user,facebook-group,twitter-search,twitter-thread,twitter-list-members,twitter-user,twitter-hashtag,twitter-list-posts}
                ...
snscrape: error: unrecognized arguments: --jsonl
```

This does not happen in the development version.

**Comment by JustAnotherArchivist** [comment] 2021-01-07 20:00
Duplicate of #77 and several others.

**Closed by JustAnotherArchivist** 2021-01-07 20:00 UTC
