### ISSUE TITLE
Get the Followers of account

### ISSUE THREAD

**Issue by sufyanhamid** [JustAnotherArchivist/snscrape#207] opened 2021-03-28 17:13 UTC
@JustAnotherArchivist hi there!! The repository is working very well for me, I just want to know that is there a way to get to Followers of an account ??just get the ids of followers/ followings.
Kindly tell me if this is possible using snscrape or some other platform or technique.

Thanks in advance :)

**Comment by JustAnotherArchivist** [comment] 2021-03-28 21:49
Duplicate of #174

**Closed by JustAnotherArchivist** 2021-03-28 21:49 UTC
