### ISSUE TITLE
Tweet' object has no attribute 'user'

### ISSUE THREAD

**Issue by VAMSIKRISHNAPALLENI** [JustAnotherArchivist/snscrape#554] opened 2022-09-16 02:43 UTC
When i'm trying to extract more information about that tweet it is giving error while accessing such as  tweet.user.location , tweet.user.username.... i am getting only limited attributes " tweet.date, tweet.id, tweet.content, tweet.username"

How can we extract that information can you please help in this

[error[](url)]([url](url))
<img width="1392" alt="Screen Shot 2022-09-15 at 10 37 02 PM" src="https://user-images.githubusercontent.com/35896751/190544959-219d73e4-7c10-49bc-85c8-5953f99f1645.png">

**Comment by JustAnotherArchivist** [comment] 2022-09-16 02:44
snscrape version?

**Comment by VAMSIKRISHNAPALLENI** [comment] 2022-09-16 02:46
snscrape==0.3.4

**Comment by JustAnotherArchivist** [comment] 2022-09-16 02:48
As suspected. You need to install the current version of snscrape (which requires Python 3.8 or higher, cf. #347).

**Comment by JustAnotherArchivist** [comment] 2022-09-16 02:50
Duplicate of #239 and others

**Closed by JustAnotherArchivist** 2022-09-16 02:50 UTC

**Comment by VAMSIKRISHNAPALLENI** [comment] 2022-09-16 05:49
I'm using python 3.8 but still facing the same issue 


<img width="1127" alt="Screen Shot 2022-09-16 at 1 49 21 AM" src="https://user-images.githubusercontent.com/35896751/190565842-9ce9d05a-43a0-4bb8-805d-dbc72bbc4856.png">



<img width="793" alt="Screen Shot 2022-09-16 at 1 47 33 AM" src="https://user-images.githubusercontent.com/35896751/190565716-24ccedcc-0590-4722-98eb-7a8956267a92.png">

**Comment by TheTechRobo** [comment] 2022-09-16 13:25
Update snscrape
