### ISSUE TITLE
How do I add proxy on CLI?

### ISSUE THREAD

**Issue by ytaijp** [JustAnotherArchivist/snscrape#166] opened 2020-12-11 10:31 UTC
snscrape --proxy-type http --proxy-host 127.1 --proxy-port 5566
 --jsonl --progress --max-results 100 twitter-search "from:jack" > user-tweets.json 

no working
i use docker tor

**Comment by JustAnotherArchivist** [comment] 2020-12-11 12:59
Duplicate of #74

**Closed by JustAnotherArchivist** 2020-12-11 12:59 UTC
