### ISSUE TITLE
Ran the code to gather 100k tweets: Fantastic Error

### ISSUE THREAD

**Issue by LRafea** [JustAnotherArchivist/snscrape#425] opened 2022-03-10 18:35 UTC
Hi there
I ran the code to gather 100k tweets and got a fantastic error 😒
![1](https://user-images.githubusercontent.com/21241695/157731490-d106b347-a925-421b-a1a9-3cbb7d084cd7.png)

Please help, I tried to understand the code but I failed!

Thanks in advance!

**Comment by JustAnotherArchivist** [comment] 2022-03-10 18:44
Duplicate of #407

**Closed by JustAnotherArchivist** 2022-03-10 18:44 UTC
