### ISSUE TITLE
Twitter 'latest' search fails with `non-200 status code (401)`

### ISSUE THREAD

**Issue by ExtremeSRL** [JustAnotherArchivist/snscrape#834] opened 2023-04-15 09:11 UTC
### Describe the bug

twitter search stop working

```pytb
File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\python311\Scripts\snscrape.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\snscrape\_cli.py", line 320, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "C:\Python311\Lib\site-packages\snscrape\modules\twitter.py", line 1659, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', _TwitterAPIType.V2, params, paginationParams, cursor = self._cursor):
  File "C:\Python311\Lib\site-packages\snscrape\modules\twitter.py", line 761, in _iter_api_data
    obj = self._get_api_data(endpoint, apiType, reqParams)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\snscrape\modules\twitter.py", line 727, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\snscrape\base.py", line 251, in _get
    return self._request('GET', *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\snscrape\base.py", line 247, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=lang%3Ait&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.
```

### How to reproduce

twitter search scraper

### Expected behaviour

retrieve twitter post 

### Screenshots and recordings

```pytb
File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\python311\Scripts\snscrape.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\snscrape\_cli.py", line 320, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "C:\Python311\Lib\site-packages\snscrape\modules\twitter.py", line 1659, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', _TwitterAPIType.V2, params, paginationParams, cursor = self._cursor):
  File "C:\Python311\Lib\site-packages\snscrape\modules\twitter.py", line 761, in _iter_api_data
    obj = self._get_api_data(endpoint, apiType, reqParams)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\snscrape\modules\twitter.py", line 727, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\snscrape\base.py", line 251, in _get
    return self._request('GET', *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\snscrape\base.py", line 247, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=lang%3Ait&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.
```

### Operating system

windows 10

### Python version: output of `python3 --version`

3.7.5

### snscrape version: output of `snscrape --version`

 0.6.1.20230315.dev2+gedac5f3

### Scraper

twitter-search

### How are you using snscrape?

CLI (`snscrape ...` as a command, e.g. in a terminal)

### Log output
```pytb
File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\python311\Scripts\snscrape.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\snscrape\_cli.py", line 320, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "C:\Python311\Lib\site-packages\snscrape\modules\twitter.py", line 1659, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', _TwitterAPIType.V2, params, paginationParams, cursor = self._cursor):
  File "C:\Python311\Lib\site-packages\snscrape\modules\twitter.py", line 761, in _iter_api_data
    obj = self._get_api_data(endpoint, apiType, reqParams)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\snscrape\modules\twitter.py", line 727, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\snscrape\base.py", line 251, in _get
    return self._request('GET', *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\snscrape\base.py", line 247, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=lang%3Ait&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.
```

### Dump of locals
```pytb
File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\python311\Scripts\snscrape.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\snscrape\_cli.py", line 320, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "C:\Python311\Lib\site-packages\snscrape\modules\twitter.py", line 1659, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', _TwitterAPIType.V2, params, paginationParams, cursor = self._cursor):
  File "C:\Python311\Lib\site-packages\snscrape\modules\twitter.py", line 761, in _iter_api_data
    obj = self._get_api_data(endpoint, apiType, reqParams)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\snscrape\modules\twitter.py", line 727, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\snscrape\base.py", line 251, in _get
    return self._request('GET', *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\snscrape\base.py", line 247, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=lang%3Ait&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.
```

### Additional context

none

**Comment by zoubidabida** [comment] 2023-04-15 09:21
Actually the error returned by twitter is : 
{"errors":[{"message":"Bad Authentication data","code":215}]}

**Comment by Yomguithereal** [comment] 2023-04-15 10:05
Related to medialab/minet#682

**Comment by Hesko123** [comment] 2023-04-15 10:16
> Related to [medialab/minet#682](https://github.com/medialab/minet/issues/682)

Don't think it is related to the latest tab as it's not something new. Snscrape was already aware about that.

**Comment by JustAnotherArchivist** [comment] 2023-04-15 10:21
> Actually the error returned by twitter is :
> {"errors":[{"message":"Bad Authentication data","code":215}]}

No, it isn't. Why do people keep opening the API URLs in browsers and expecting it to work despite lacking the relevant authentication headers?

Yes, looks like Twitter removed the 'latest' search again. Unless they reverse that, it's unlikely that there is a fix for this. Cf. #634 for the previous occurrence of this a couple months ago.

**Comment by JustAnotherArchivist** [comment] 2023-04-15 10:39
For the record, the error returned by Twitter is:

    {"errors":[{"code":32,"message":"Could not authenticate you."}]}

**Comment by Mr-Freewan** [comment] 2023-04-15 10:49
Same error in TwitterUserScraper. Not only search. Moreover, there was a short period of time when it worked, but after about 10 minutes it broke again

**Comment by JustAnotherArchivist** [comment] 2023-04-15 10:51
It is only the latest search, but `twitter-user`, `twitter-hashtag`, and a few more scrapers are simple wrappers around the search, so yes, they're also affected.

**Comment by Mr-Freewan** [comment] 2023-04-15 10:55
I noticed that it works, but it is very unstable. It gives an error (non-200 (401)) in 2 out of 3 requests, but it works fine on 3.

**Comment by projectno3** [comment] 2023-04-15 11:20
Using "top = True" as suggested above works for me. I however get the message "Stopping after 20 empty pages" and I only get exactly 91 Tweets per search, although more Tweets exist. Is there a way to work around this limit? Thank you very much in advance!

**Comment by Mr-Freewan** [comment] 2023-04-15 11:34
It worked again =)

**Comment by JustAnotherArchivist** [comment] 2023-04-15 16:52
Haven't seen any further interruptions, but I'll keep the issue open and pinned for now in case it returns.

**Comment by JustAnotherArchivist** [comment] 2023-04-17 17:23
No more issues since Saturday. :-)

**Comment by ExtremeSRL** [comment] 2023-04-17 17:27
twitter these days is making changes to the business plans and I guess therefore also to the API.
Let's stay tuned because I'm afraid there will be more problems.
In the meantime always thanks for your great work!

**Comment by projectno3** [comment] 2023-04-20 11:46
Same here. At first it was just unstable, but now it stopped working completely.

**Comment by rmnhg** [comment] 2023-04-20 12:26
I only have this problem with twitter-user. twitter-search runs fine

**Comment by JustAnotherArchivist** [comment] 2023-04-20 12:29
@rmnhg No, it happens with both. twitter-user is a very thin wrapper around twitter-search anyway; wouldn't make any sense if they didn't behave the same. You probably just got lucky on your twitter-search runs and unlucky on the twitter-user ones.

**Comment by Mr-Freewan** [comment] 2023-04-20 12:54
It works, but it is very unstable. Apparently Twitter is doing some work on its servers again.

**Comment by codilau** [comment] 2023-04-20 13:10
What I see is that unauthenticated searches fail even in the browser. "Your account may not be allowed to perform this action. Please refresh the page and try again."

**Comment by kooperalan** [comment] 2023-04-20 13:11
I set a delay of 1 minute between each tweet and it works.

**Comment by Josias-TopicWorx** [comment] 2023-04-20 13:21
Issue seems to persist for me, every other request returns data.

**Comment by JustAnotherArchivist** [comment] 2023-04-20 13:36
I can't reproduce it anymore since a few minutes ago. All my test searches seem to succeed now.

**Comment by Mr-Freewan** [comment] 2023-04-20 14:33
It looks like the problem will persist until the work on the servers is completed

**Comment by Isid28** [comment] 2023-04-20 14:35
for how long because i need the data for my thesis ?

**Comment by 0xTechnician** [comment] 2023-04-20 14:40
> 

What are you referring to? By work on the servers? Was there any communication about it ? Seems unlikely since its a private API.

**Comment by 0xTechnician** [comment] 2023-04-20 14:41
> It looks like the problem will persist until the work on the servers is completed
> 
> p.s. delay doesn't work for me (=


What are you referring to by "work on the servers"? Was there any communication about it ? Seems unlikely since its a private API.

**Comment by Hesko123** [comment] 2023-04-20 15:42
Hope it ends well. AntoinePaix, please do something to save us ! 🤣

**Comment by Hesko123** [comment] 2023-04-20 16:01
It works again for me ! 🚀

**Comment by zorrobiwan** [comment] 2023-04-20 16:05
For me too (through a lambda function in eu-west-3)

**Comment by AntoinePaix** [comment] 2023-04-20 16:41
I have the same error with my own scraper and a complete different implementation (I use http). The 'top' tab works well but not the 'latest' tab.

But last night the advanced search was working fine with 'latest'...

**Comment by Hesko123** [comment] 2023-04-20 16:46
> I have the same error with my own scraper and a complete different implementation (I use http). The 'top' tab works well but not the 'latest' tab.
> 
> But last night the advanced search was working fine with 'latest'...

What's the advantage of using http implementation ?

**Comment by AntoinePaix** [comment] 2023-04-20 17:02
@Hesko123 The response hook system of httpx is designed to call a function just before the request is sent or just after you receive a response.

**Comment by Hesko123** [comment] 2023-04-20 17:03
> @Hesko123 The response hook system of httpx is designed to call a function just before the request is sent or just after you receive a response.

Merci le boss ! J'ai vue que tu venais de jvc aussi ;)

**Comment by AntoinePaix** [comment] 2023-04-20 17:06
@Hesko123 On vit dans un petit monde ^^

**Comment by Hesko123** [comment] 2023-04-20 17:15
> @Hesko123 On vit dans un petit monde ^^

Tbh I am pretty scared since Elon musk acquired twitter. You told me that this case is occasional but why is it happening, do we have a workaround for this issue ? It seems to be twitter side and we can't do anything on top of that.0.

**Comment by mc0ps** [comment] 2023-04-20 18:07
> @Hesko123 async like if you want to run multiple scrapers inside one thread.
> 
> Twitter's problem with the 'latest' search is really episodic. I just ran my personal scraper several times, the first 2 failed but the third passed without issue.

It seems almost random (just worked 1/5 times for me). I'm wondering if it has something to do with the user-agent, because I noticed that it's set randomly.

**Comment by AntoinePaix** [comment] 2023-04-20 18:31
It's quite weird but when I copy as curl the request made to the `adaptive.json` API, if I remove the cookies I have 1/3 the authentication error.

But if I put the cookies back with only the "guest_id" cookie I have the impression that I no longer have the authentication problem...

**Comment by dengkefeng** [comment] 2023-04-20 18:43
I see snscrape call twitter by using twitter api "https://api.twitter.com/2/search/adaptive.json"，so is it going to be affected by twitter new policy with very small free rate limit. Is there a plan to fix this problem, like supporting scrape twitter by webpage (e.g: https://twitter.com/search?q=from%3Aelonmusk&src=typed_query&f=live)?

**Comment by JustAnotherArchivist** [comment] 2023-04-20 18:47
@dengkefeng #695

**Comment by JustAnotherArchivist** [comment] 2023-04-20 18:54
@AntoinePaix Negative, I'm also seeing failures with the `guest_id` cookie set.

**Comment by dengkefeng** [comment] 2023-04-20 18:57
> @dengkefeng #695

Got it, thanks @JustAnotherArchivist very much. So how do we resolve the main issue in this thread? Just wait for twitter to come back? Thanks!

**Comment by AntoinePaix** [comment] 2023-04-20 19:00
@JustAnotherArchivist Ah darn. Finally it is rather good news, it means that it is not necessarily a problem related to a new method of authentication.

**Comment by laurent-IA** [comment] 2023-04-20 22:21
the search function is no more accessible if you are not logged in . . so I suppose it is the end for snscrape

**Comment by JustAnotherArchivist** [comment] 2023-04-20 22:37
The error is now `blocked (403)`, and all requests seem to be affected. No indication of what's happening on the web interface though, just 'Please refresh the page and try again', so it may well be unintentional.

**Comment by pablorm296** [comment] 2023-04-20 22:53
Maybe earlier today we were witnessing a canary deploy that directed x% of the traffic to this new version where the search feature and the guest token are no longer available :disappointed:

**Comment by Mr-Freewan** [comment] 2023-04-20 23:15
@JustAnotherArchivist, can you scrape tweets from a profile page? (by a direct link to this profile)

**Comment by MrCabss69** [comment] 2023-04-20 23:16
https://developer.twitter.com/en/products/twitter-api 

100$/month for 10k tweet read limit cap and they limit almost all the guest searches by now ... LOL

**Comment by lsalvinien** [comment] 2023-04-20 23:26
> The error is now `blocked (403)`, and all requests seem to be affected. No indication of what's happening on the web interface though, just 'Please refresh the page and try again', so it may well be unintentional.

Go on Twitter.Com
Logout if you are logged in
And you will see the page has changed, there is no more the search feature

I doubt it is unintentional

**Comment by JustAnotherArchivist** [comment] 2023-04-21 01:10
Closing this issue as this is no longer the problem affecting everyone. See #846 instead.

**Closed by JustAnotherArchivist** 2023-04-21 01:10 UTC
Labels: bug, module:twitter, upstream

**Comment by Reimao** [comment] 2023-07-01 00:17
It seems to be happening again with `Error: blocked (404)`
