### ISSUE TITLE
Multiple Inheritance With NamedTuple is not supported

### ISSUE THREAD

**Issue by JosiasAurel** [JustAnotherArchivist/snscrape#237] opened 2021-06-05 00:12 UTC
I have just installed snscrape to scrape some twitter content. When I type `snscrape --help` or any other command, it outputs the following error

Platform Info
- Windows 10
- Python 3.9

```shell
Traceback (most recent call last):
  File "c:\users\sndem\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\sndem\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sndem\AppData\Local\Programs\Python\Python39\Scripts\snscrape.exe\__main__.py", line 7, in <module>
  File "c:\users\sndem\appdata\local\programs\python\python39\lib\site-packages\snscrape\cli.py", line 224, in main
    args = parse_args()
  File "c:\users\sndem\appdata\local\programs\python\python39\lib\site-packages\snscrape\cli.py", line 159, in parse_args
    import snscrape.modules
  File "c:\users\sndem\appdata\local\programs\python\python39\lib\site-packages\snscrape\modules\__init__.py", line 15, in <module>
    _import_modules()
  File "c:\users\sndem\appdata\local\programs\python\python39\lib\site-packages\snscrape\modules\__init__.py", line 12, in _import_modules
    module = importlib.import_module(moduleName)
  File "c:\users\sndem\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\sndem\appdata\local\programs\python\python39\lib\site-packages\snscrape\modules\facebook.py", line 14, in <module>
    class FacebookPost(typing.NamedTuple, snscrape.base.Item):
  File "c:\users\sndem\appdata\local\programs\python\python39\lib\typing.py", line 1881, in _namedtuple_mro_entries
    raise TypeError("Multiple inheritance with NamedTuple is not supported")
TypeError: Multiple inheritance with NamedTuple is not supported
```

**Comment by JustAnotherArchivist** [comment] 2021-06-05 00:14
Duplicate of #111 and #224

**Closed by JustAnotherArchivist** 2021-06-05 00:14 UTC

**Comment by JosiasAurel** [comment] 2021-06-05 00:16
Okay. Things got fixed when i installed straight from the repo rather than `pip`

**Comment by JustAnotherArchivist** [comment] 2022-11-17 01:25
@firefling-SenapatiRajesh This was fixed ages ago. You can just install normally.
