### ISSUE TITLE
 TypeError: __init__() missing 1 required positional argument: 'title'

### ISSUE THREAD

**Issue by sebastienhouzet** [JustAnotherArchivist/snscrape#423] opened 2022-03-09 20:05 UTC
hello, error after 1440 tweet received

snscrape --with-entity --jsonl --dump-locals twitter-user XXX > XXX.json

CRITICAL  snscrape._cli  Dumped stack and locals to /tmp/snscrape_locals_wboera4s
Traceback (most recent call last):
  File "/usr/local/bin/snscrape", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/snscrape/_cli.py", line 308, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/usr/local/lib/python3.8/dist-packages/snscrape/modules/twitter.py", line 883, in get_items
    yield from super().get_items()
  File "/usr/local/lib/python3.8/dist-packages/snscrape/modules/twitter.py", line 811, in get_items
    yield from self._v2_timeline_instructions_to_tweets(obj)
  File "/usr/local/lib/python3.8/dist-packages/snscrape/modules/twitter.py", line 488, in _v2_timeline_instructions_to_tweets
    yield from self._v2_instruction_tweet_entry_to_tweet(entry['entryId'], entry['content'], obj)
  File "/usr/local/lib/python3.8/dist-packages/snscrape/modules/twitter.py", line 511, in _v2_instruction_tweet_entry_to_tweet
    yield self._tweet_to_tweet(tweet, obj)
  File "/usr/local/lib/python3.8/dist-packages/snscrape/modules/twitter.py", line 640, in _tweet_to_tweet
    kwargs['quotedTweet'] = self._tweet_to_tweet(obj['globalObjects']['tweets'][tweet['quoted_status_id_str']], obj)
  File "/usr/local/lib/python3.8/dist-packages/snscrape/modules/twitter.py", line 642, in _tweet_to_tweet
    kwargs['card'] = self._make_card(tweet['card'], _TwitterAPIType.V2)
  File "/usr/local/lib/python3.8/dist-packages/snscrape/modules/twitter.py", line 632, in _make_card
    return Card(**cardKwargs)
TypeError: __init__() missing 1 required positional argument: 'title'

**Comment by JustAnotherArchivist** [comment] 2022-03-09 20:06
Duplicate of #407

**Closed by JustAnotherArchivist** 2022-03-09 20:06 UTC
