### ISSUE TITLE
Setting a limit to maximum number of tweets extracted per day using snscrape

### ISSUE THREAD

**Issue by PriyankaPGowdaa** [JustAnotherArchivist/snscrape#164] opened 2020-12-07 11:28 UTC
I need to scrape tweets based on a search query for one month. My code is extracting many tweets from 7 to 10 days and nothing from the remaining days when I set the maximum limit. Is there a way I can set a limit of say, maximum100 tweets per day to extract a total of 3000 tweets for the whole month rather than multiple tweets in a short timeframe. Or if there is a way to extract top most liked tweets per day and set a limit? How would I implement it in the below code? I would greatly appreciate it. Thanks 

```python
maxTweets =3000

# Creating list to append tweet data to
tweets_list = []
keyword = 'COVID-19'

for i,tweet in enumerate(sntwitter.TwitterSearchScraper(keyword + ' since:2020-11-01 until:2020-12-06 lang:"en" ').get_items()):
    if i>maxTweets:
        break
    covidtweets_list.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.user.location,
                             tweet.likeCount,tweet.retweetCount, tweet.user.followersCount])
```

**Comment by JustAnotherArchivist** [comment] 2020-12-07 19:06
The only way to retrieve some fixed number of tweets per day is to run `TwitterSearchScraper` once for each day with an appropriate query, e.g. `since:2020-11-01 until:2020-11-02` to fetch tweets from 1 Nov. However, this will always retrieve the most recent tweets per day, which is likely not very useful. Retrieving top tweets is not yet supported (#109). You could use `min_faves:123` (or `min_retweets`, `min_replies`) to only get tweets that were liked at least some number of times, but there is no way to sort them directly through the search query, so you'd have to collect all results and then do that yourself if you want the N most-liked tweets.

**Comment by JustAnotherArchivist** [comment] 2020-12-07 19:08
Also, this is very similar to #152, so closing as a duplicate of that.

**Closed by JustAnotherArchivist** 2020-12-07 19:08 UTC

**Comment by PriyankaPGowdaa** [comment] 2020-12-11 08:48
Thanks for the response. If I cannot retrieve some fixed number of tweets per day, is there a way I could fetch say,1000 'random' tweets with a keyword for a certain timeframe instead of collecting all the tweets in the order it was posted?

**Comment by JustAnotherArchivist** [comment] 2020-12-11 13:05
No, snscrape can only extract the reverse-chronological 'latest' results currently.

**Comment by hannahgkeel** [comment] 2021-04-17 15:41
Are there any updates on this? I am trying to scrape 200k "random" tweets from a timeframe of about a year but right now I am only getting the "latest" two months. Has there been an update that includes some type of random keyword?

**Comment by JustAnotherArchivist** [comment] 2021-04-17 16:05
No. Unless Twitter adds a search operator like that (very unlikely), it isn't possible to ever implement this in snscrape. To get a truly random sample, you have to collect all tweets in that time frame and then sample from that locally.

**Comment by lolakhairy** [comment] 2021-12-07 05:19
any update in this
