### ISSUE TITLE
Facebook Module AssertionError

### ISSUE THREAD

**Issue by TheTechRobo** [JustAnotherArchivist/snscrape#245] opened 2021-06-30 22:38 UTC
It was working like 2 seconds ago... Sorry if this is Yet Another Dumb "Issue"™...

In 0.3.5, I'm getting an AssertionError...

```
╰─$ snscrape --dump-locals facebook-user TheXKCD > facebooklist.txt                                                              1 ↵
2021-06-30 18:36:00.402  CRITICAL  snscrape._cli  Dumped stack and locals to /tmp/snscrape_locals_lrcblsg3
Traceback (most recent call last):
  File "/home/thetechrobo/.local/bin/snscrape", line 11, in <module>
    load_entry_point('snscrape==0.3.5.dev118+g2bb706f', 'console_scripts', 'snscrape')()
  File "/home/thetechrobo/.local/lib/python3.8/site-packages/snscrape/_cli.py", line 280, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/home/thetechrobo/.local/lib/python3.8/site-packages/snscrape/modules/facebook.py", line 194, in get_items
    assert 'domops' in response
AssertionError
```
Here's the stack output: http://paste.openstack.org/show/807089

**Comment by JustAnotherArchivist** [comment] 2021-06-30 23:18
Duplicate of #208

**Closed by JustAnotherArchivist** 2021-06-30 23:18 UTC

**Comment by TheTechRobo** [comment] 2021-07-01 01:46
Ah shit, sorry again.
