### ISSUE TITLE
TypeError: Multiple inheritance with NamedTuple is not supported

### ISSUE THREAD

**Issue by chaituc** [JustAnotherArchivist/snscrape#524] opened 2022-07-27 08:09 UTC
> ` import snscrape.modules.twitter as sntwitter`

TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_13144/2714111727.py in <module>
----> 1 import snscrape.modules.twitter as sntwitter
      2 import pandas as pd

~\Anaconda3\lib\site-packages\snscrape\modules\__init__.py in <module>
     13 
     14 
---> 15 _import_modules()

~\Anaconda3\lib\site-packages\snscrape\modules\__init__.py in _import_modules()
     10                         # Import module if not already imported
     11                         moduleName = f'snscrape.modules.{fn[:-3]}'
---> 12                         module = importlib.import_module(moduleName)
     13 
     14 

~\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

~\Anaconda3\lib\site-packages\snscrape\modules\facebook.py in <module>
     12 
     13 
---> 14 class FacebookPost(typing.NamedTuple, snscrape.base.Item):
     15         cleanUrl: str
     16         dirtyUrl: str

~\Anaconda3\lib\typing.py in _namedtuple_mro_entries(bases)
   1899 def _namedtuple_mro_entries(bases):
   1900     if len(bases) > 1:
-> 1901         raise TypeError("Multiple inheritance with NamedTuple is not supported")
   1902     assert bases[0] is NamedTuple
   1903     return (_NamedTuple,)

TypeError: Multiple inheritance with NamedTuple is not supported

**Comment by JustAnotherArchivist** [comment] 2022-07-27 14:26
Duplicate of #111

**Closed by JustAnotherArchivist** 2022-07-27 14:26 UTC

**Comment by chaituc** [comment] 2022-07-28 05:58
This code works fine in other machines, facing issues with my system only. Can you please help me understand why that is?

**Comment by TheTechRobo** [comment] 2022-07-28 13:42
Do you have an outdated version of snscrape installed? Try `snscrape --version`

**Comment by chaituc** [comment] 2022-08-03 06:39
snscrape==0.4.3.20220106
I have this. is this the outdated one?

**Comment by JustAnotherArchivist** [comment] 2022-08-03 07:32
That is not the code you're running. You might have two different installations of snscrape. Try `import snscrape.version; print(snscrape.version.__version__)` in the same environment as you ran the `import` in the first message here.
