### ISSUE TITLE
Limit to number of tweets when scraping with sncrape?

### ISSUE THREAD

**Issue by JSMboli** [JustAnotherArchivist/snscrape#178] opened 2020-12-30 03:01 UTC
Hi everyone,
I have been searching for the limits on the number of tweets one can scrape with snscrape. 
Please is there any limit or it is limitless? 
Thank you.

**Comment by JustAnotherArchivist** [comment] 2020-12-30 04:19
Please use the search before opening issues (see also the pinned issue).

Duplicate of #69 and #76.

**Closed by JustAnotherArchivist** 2020-12-30 04:19 UTC
