### ISSUE TITLE
jsonl not being recognized as an argument

### ISSUE THREAD

**Issue by gregoirelm** [JustAnotherArchivist/snscrape#305] opened 2021-11-12 01:57 UTC
Hi there! I'm getting the following error when trying to use --jsonl as an argument:
snscrape: error: unrecognized arguments: --jsonl
Please let me know if you know what might be wrong.
Thank you

**Comment by JustAnotherArchivist** [comment] 2021-11-12 02:43
Duplicate of #77

**Closed by JustAnotherArchivist** 2021-11-12 02:43 UTC
