### ISSUE TITLE
AttributeError: module 'functools' has no attribute 'cached_property'

### ISSUE THREAD

**Issue by lukaspistelak** [JustAnotherArchivist/snscrape#86] opened 2020-09-25 15:15 UTC
```
    import snscrape.modules
  File "/usr/local/lib/python3.6/dist-packages/snscrape/modules/__init__.py", line 3, in <module>
    import snscrape.base
  File "/usr/local/lib/python3.6/dist-packages/snscrape/base.py", line 55, in <module>
    class Scraper:
  File "/usr/local/lib/python3.6/dist-packages/snscrape/base.py", line 75, in Scraper
    @functools.cached_property
AttributeError: module 'functools' has no attribute 'cached_property'
```
THE OS :  ubuntu 18.04

but the version from pip works 0.3.4 !

**Comment by JustAnotherArchivist** [comment] 2020-09-25 15:34
Duplicate of #75. You need Python 3.8.

**Closed by JustAnotherArchivist** 2020-09-25 15:34 UTC
Labels: duplicate

**Comment by lukaspistelak** [comment] 2020-09-25 16:12
ok, but my project depends on cca 100 libs in python 3.6.9 , so you can imagine how many libs i cant use ..... can u change it please? for 3.6.9

**Comment by JustAnotherArchivist** [comment] 2020-09-25 16:33
Sorry, snscrape depends on a feature that is only available since Python 3.8.

If you want, you can try to patch snscrape. This error is the only 3.8 dependency at the moment, so you can probably get away with using `@property` instead of `@functools.cached_property`. However, expect more things to break in the future as the code will depend more and more on new language features over time.

**Comment by lukaspistelak** [comment] 2020-09-26 08:48
What you mean exactly access the entity multiple times ?, 
i Run the Twitter search Class in thread, Bad in every thread I initialize The your Twitter Search Method

**Comment by JustAnotherArchivist** [comment] 2020-09-26 13:50
`TwitterUserScraper` has an `entity` attribute that provides information on the user. This information is cached, and the retrieval is implemented with that in mind, i.e. that the underlying method is not called more than once. If you use `@property` instead of `@functools.cached_property`, that guarantee is broken.
If you only use the `TwitterSearchScraper` or do not access the `entity` (more than once per scraper instance), it is safe to replace it.
