### ISSUE TITLE
Need help scraping following Attributes/Fields that need to be scraped out of Twitter

### ISSUE THREAD

**Issue by solaiman-islam** [JustAnotherArchivist/snscrape#594] opened 2022-11-22 17:29 UTC
### Fields to Scrape from Twitter tweet: 
- Every Commenter Name,
- Commenter profile URL,
- Comment time,
- Comment text/content,
- Who Retweets,
- Retweeted Text,
- Retweeter's URL

**Comment by JustAnotherArchivist** [comment] 2022-11-22 17:32
Duplicate of #527

**Closed by JustAnotherArchivist** 2022-11-22 17:32 UTC
