### ISSUE TITLE
Twitter snscrape 'error retrieving ....  unable fo find guest token 4 requests to ..... failed giving up' 

### ISSUE THREAD

**Issue by aniyaredhead** [JustAnotherArchivist/snscrape#349] opened 2022-01-06 13:59 UTC
Hi, 
I am running the following code on a jupyter notebook
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#IBM lang:en since:2015-01-01 until:2015-02-01 exclude:replies exclude:links').get_items()):
    if i>1000:
        break
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
tweets_df2 = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])
Unfortunately, I get this error:
Error retrieving https://twitter.com/search?f=live&lang=en&q=%23IBM+lang%3Aen+since%3A2015-01-01+until%3A2015-02-01+exclude%3Areplies+exclude%3Alinks&src=spelling_expansion_revert_click: unable to find guest token
4 requests to https://twitter.com/search?f=live&lang=en&q=%23IBM+lang%3Aen+since%3A2015-01-01+until%3A2015-02-01+exclude%3Areplies+exclude%3Alinks&src=spelling_expansion_revert_click failed, giving up
The code worked fine for 50 previous twitter accounts. I am working with python 3.8 on Windows 10. How can I fix this please? 
Thanks in advance.

**Comment by cabarbato** [comment] 2022-01-06 14:50
I just had this same issue too. I noticed there were some pretty recent updates to the repo so I just upgraded my version from 0.4.2 to 0.4.3 on python3.8 and it appears to work now, hopefully that could help you as well.

**Comment by aniyaredhead** [comment] 2022-01-06 14:57
> 

thanks for your help but how can I update it?

**Comment by cabarbato** [comment] 2022-01-06 15:04
You should be able to run either `python3.8 -m pip install --upgrade snscrape` or `pip3 install --upgrade snscrape`

**Comment by aniyaredhead** [comment] 2022-01-06 15:13
> pip3 install --upgrade snscrape

I did it and it worked fine! Thank you so much you made my day!

**Comment by JustAnotherArchivist** [comment] 2022-01-07 16:46
Duplicate of #347

**Closed by JustAnotherArchivist** 2022-01-07 16:46 UTC
Labels: duplicate
