### ISSUE TITLE
TypeError: Multiple inheritance with NamedTuple is not supported

### ISSUE THREAD

**Issue by amith531** [JustAnotherArchivist/snscrape#256] opened 2021-07-19 05:39 UTC
```
W:\>snscrape --max-results 100 twitter-hashtag archiveteam
Traceback (most recent call last):
  File "w:\programdata\anaconda3\envs\voter_data\lib\runpy.py", line 197, in _run_module_as_main 
    return _run_code(code, main_globals, None,
  File "w:\programdata\anaconda3\envs\voter_data\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "W:\ProgramData\Anaconda3\envs\voter_data\Scripts\snscrape.exe\__main__.py", line 7, in <module>
  File "w:\programdata\anaconda3\envs\voter_data\lib\site-packages\snscrape\cli.py", line 224, in main
    args = parse_args()
  File "w:\programdata\anaconda3\envs\voter_data\lib\site-packages\snscrape\cli.py", line 159, in parse_args
    import snscrape.modules
  File "w:\programdata\anaconda3\envs\voter_data\lib\site-packages\snscrape\modules\__init__.py", line 15, in <module>
    _import_modules()
  File "w:\programdata\anaconda3\envs\voter_data\lib\site-packages\snscrape\modules\__init__.py", line 12, in _import_modules
    module = importlib.import_module(moduleName)
  File "w:\programdata\anaconda3\envs\voter_data\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "w:\programdata\anaconda3\envs\voter_data\lib\site-packages\snscrape\modules\facebook.py", line 14, in <module>
    class FacebookPost(typing.NamedTuple, snscrape.base.Item):
  File "w:\programdata\anaconda3\envs\voter_data\lib\typing.py", line 1881, in _namedtuple_mro_entries
    raise TypeError("Multiple inheritance with NamedTuple is not supported")
TypeError: Multiple inheritance with NamedTuple is not supported 
```

**Comment by JustAnotherArchivist** [comment] 2021-07-19 16:13
Duplicate of #111

**Closed by JustAnotherArchivist** 2021-07-19 16:13 UTC
