### ISSUE TITLE
ERROR in TwitterSearchScraper "__init__() missing 1 required positional argument: 'title'"

### ISSUE THREAD

**Issue by ricardonunesoliveira** [JustAnotherArchivist/snscrape#448] opened 2022-04-11 11:23 UTC
![image](https://user-images.githubusercontent.com/62619730/162729445-aa902acc-e43d-4727-8a64-7dd35458e51d.png)

If i change the number of tweets, the dates of since and until or depending of the words in the query i get this error below...
![image](https://user-images.githubusercontent.com/62619730/162729723-6f50d42b-18ff-4b6d-8745-2a4c9f228f2b.png)

 i want to understand how to avoid it...

**Comment by JustAnotherArchivist** [comment] 2022-04-11 11:24
Duplicate of #407

**Closed by JustAnotherArchivist** 2022-04-11 11:24 UTC
